src/LoginForm/LoginForm.js
src/RegistrationForm/RegistrationForm.js

Fixes issue with password manager not always recognising username field when registering a new account, changing password when logged in or resetting password. Fix was actually a simple one in the end and just required autocomplete on the email fields to be set to username. Have tested all password components using Chrome & Edge password managers and now username (email address in our case) is correctly picked up.
Closes https://github.com/IPG-Automotive-UK/react-ui/issues/98

Password manager integration

---

src/Select/Select.js
src/Select/Select.stories.js
src/Select/Select.test.js

Added new error prop to the Select componet so it can be controlled outside the component. Prior to this the component itself had some built-in logic to decide when to show the error state. This obviously isn't that useful if you want to control the error state yourself in an app (as I do).

Add error prop to Select component

---

src/ThemeProvider/ThemeProvider.js

Added some negative margin to reduce the whitespace when an accordion is expanded as noticed in https://github.com/IPG-Automotive-UK/ngd/pull/560
Before
After

add negative margin when accordion summary is expanded

---

src/Sidebar/SidebarItem/SidebarItem.js
src/Sidebar/SidebarItem/SidebarItem.stories.js

Added two new props to SidebarItem to allow custom styling to be passed in to the icon and text components. There are two new stories to show how to use them.

SidebarItem styling props

---

src/Autocomplete/Autocomplete.stories.js
src/FontPicker/FontPicker.js
src/FontPicker/FontPicker.stories.js
src/FontPicker/FontPicker.test.js
src/FontPicker/index.js
src/Sidebar/Sidebar.stories.js
src/index.js

Contributes to https://github.com/IPG-Automotive-UK/instrument-designer/issues/59
New font picker component. Allows selection of a font family from an autocomplete dropdown. A set of default font options are provided but a custom font options list can also be provided. The dropdown options and the currently selected item are displayed in the corresponding font.
Also fixed a couple of storybook warnings with the Autocomplete and Sidebar components along the way.
Can be tested at https://deploy-preview-274--ipguk-react-ui.netlify.app/?path=/story/general-fontpicker--default

Font picker

---

src/FontStyle/FontStyle.js
src/FontStyle/FontStyle.stories.js
src/FontStyle/FontStyle.test.js
src/FontStyle/index.js
src/index.js

Contributes to https://github.com/IPG-Automotive-UK/instrument-designer/issues/14
New component added to toggle font style options (bold, italic, underline).
Can be tested at https://deploy-preview-280--ipguk-react-ui.netlify.app/?path=/story/text-fontstyle--default

Font style component

---

src/NumberField/NumberField.js

fixed helper message. Previously the message would say value has to be greater than "min" or less than "max" when in fact the value could be greater than or equal to min or less than equal to max.

fixed helper text  error message to be reflective of actual conditions.

---

src/Snackbar/Snackbar.js

Closes https://github.com/IPG-Automotive-UK/instrument-designer/issues/133
Fixed issue with the close button in snackbar showing as an elipse rather than circle when hovering over it. This was introduced during the recent migration to MUI 5 with updated styling. As well as make it circular again I have also knocked down the size a little bit as it was overwhelming the snackbar a bit too much.

Fix close button size

---

src/Color/Color.js
src/Color/Color.stories.js
src/Color/Color.test.js
src/MultiColor/MultiColor.js

Removed the popover dialog and swatch from the color component. Color component is now just a standalone color selector component that can be parented wherever required. If a particular app requires it in a popover it can parent it so. We have a usecase in ID that doesn't require the color component with swatch and popover and instead we just want the core color selector parts. This has also significantly simplified the component with less props and less code to deal with popover related stuff.
Multi-color also required updating as it uses the color component internally.

Remove popover from color component

---

src/Color/Color.js

Fixes two issues with color component we spotted in one of our apps.
Value prop was not being kept in sync with internal state. I've removed the internal state now as there was no need for it and we can just use the value prop directly. I also removed useMemo which wasn't necessary where it was being used. You could see the behaviour in storybook where you could change the value using the color picker in storybook prop but the color component wasn't actually updated.
https://user-images.githubusercontent.com/8976377/195438434-2dd7ca46-d983-4fec-a23f-97473fccdbb5.mov
https://user-images.githubusercontent.com/8976377/195438124-12b5f529-8aba-4b4b-b2bb-a29709f0a71c.mov
If you pressed delete on one of the input number fields, e.g. the red field, then all color fields had got set to 0. Pressing …

Color controlled state

---

.storybook/main.js
.storybook/preview.js
package-lock.json
package.json
src/ThemeProvider/ThemeProvider.js

Added storybook dark mode controls, and synced our ThemeProvider with it. This allows us to test what our components look like in dark mode via storybook.
Idea from: https://github.com/IPG-Automotive-UK/react-ui/pull/467#issuecomment-1285082876

Storybook dark/light mode

---

src/ModelButton/ModelButton.js
src/ModelButton/ModelButton.stories.js
src/ModelButton/ModelButton.test.js
src/ModelButton/index.js
src/index.js

Contributes to TD-1273.
Added a new model button component as per https://www.figma.com/file/B75H0DFTEiUFjJtehIKa8M/Model-Manager?node-id=1451%3A53435&t=WpgDwwhWuRpQtzje-1
Component accepts props for disabled, icon, label, onClick and status. Styled as per Figma. Border color is set based on the status prop (none, error, warning or success). Hover effect changes border and icon to blue. Supports dark and light mode.
There will be a separate PR for the ModelButtonGroup component which will accept this ModelButton as children.

Model button component

---

src/ModelButton/ModelButton.js
src/ModelButton/ModelButton.stories.js

Contributes to https://sce.myjetbrains.com/youtrack/issue/TD-1273/Create-new-model-class-button-component
Updated the ModelButton component to allow children to be nested to achieve this design shown below. Figma design can be found at https://www.figma.com/file/B75H0DFTEiUFjJtehIKa8M/Model-Manager?node-id=1027%3A61058&t=fJAD4DsnYV3fwNKM-1
https://user-images.githubusercontent.com/8976377/216949709-c342b98e-18b7-49ad-9c69-bf8268906687.mov
When @mattcorner and I originally discussed the design we were thinking of this syntax with a new ModelButtonGroup parent.
```
<ModelButtonGroup>
<ModelButton />
<ModelButton />
<ModelButton />
</ModelButtonGroup>
```
But when I got into the dev it made more sense to allow ModelButton to have ModelButton children as the styling for the notch and popup …

Model button grouping

---

src/AppHeader/AppHeader.js
src/ThemeProvider/ThemeProvider.js

As I was reviewing the new app layout component integration with our apps I noticed that dark mode primary color was wrong. You can see sidebar items were wrong color compared to Figma and so was anything in our apps that was using primary color, e.g. the plots in results app.
Before:
Now:

Fix dark mode primary color

---

src/ModelButton/ModelButton.js

This is a fix for the ModelButton broken style in the storybook.
this
to this

fix for model button style broken

---

src/Wizard/Wizard.js

- A small update to the Wizard title font weight to match the new Figma
Figma
this
to this

font-weight updated

---

src/AppHeader/AppHeader.js
src/AppHeader/AppHeader.stories.js
src/AppLauncher/AppLauncher.js
src/AppLauncher/AppLauncher.stories.js
src/AppLayout/AppLayout.js
src/AppLayout/AppLayout.stories.js

Contributes to TD-1604.
Now that each app is served from a sub-path relative to a base URL, rather than sub-domains, we no longer need to manage links for each app. Instead we can just pass a base URL and then fix the relative links for each app inside the React-UI component. This simplifies usage in each app and reduces the number of environment variables down to just one for the base URL rather than the current implementation requiring a variable for each app.
AppLauncher is the component that contains the links for each app in the dropdown drawer. This now has a new url prop which replaces appUrls. The URL links for each app are then fixed inside this component relative to the base URL. AppLayout is the top level component we actually use in each app and this propagates the baseUrl …

Switch to relative app links

---

src/LabelSelector/LabelChip/LabelChip.js

LabelChip is showing the Roboto font rather than the Montserra font as raised by @Sowbhagya-ipg
We were wrapping each Chip in its own ThemeProvider to override its colour, but this also overrode everything in our React-UI ThemeProvider meaning we lost the font. I've removed the wrapping ThemeProvider and instead styled it using the sx prop so that we get the best of both worlds.
* Open Storybook
* Inspect the element
* Check font shows as Montserra
https://user-images.githubusercontent.com/27866636/231391246-02f456ba-adf6-41f7-a899-ac0f4b3fae0d.mov

Correct LabelChip font

---

.github/workflows/test.yml
package-lock.json
package.json
src/Sidebar/Sidebar.stories.tsx
src/Sidebar/SidebarItem/SidebarItem.stories.tsx
src/Sidebar/SidebarItem/SidebarItem.tsx
src/Sidebar/SidebarItem/SidebarItem.types.ts

relates to https://github.com/IPG-Automotive-UK/cloud-licensing-web/issues/274
-  The sidebar items in cloud licensing have an Icon with text underneath it (stacked) rather than the default inline icon and text that is currently available.
This PR enables to user to pass in an optional display property which can be either "inline" or "stacked" which will allow the user to specifically set the orientation of the icon and text in the sidebar item. The default behavior of this component is maintained as the default value of the display property is "inline". 
-  In order to reduce code duplication I have created separate components inside sidebar item for the Count badge and the expand icon so that I can use them for both the SidebarInLine and SidebarStacked components. 
- The SidebarInLine …

Feature/sidebar icon item 

---

src/Snackbar/Snackbar.js
src/Snackbar/Snackbar.stories.tsx
src/Snackbar/Snackbar.test.tsx
src/Snackbar/Snackbar.tsx
src/Snackbar/Snackbar.types.ts
src/Snackbar/index.js
src/Snackbar/index.ts
src/index.ts

Fixes an issue spotted in a cloud licensing pull request https://github.com/IPG-Automotive-UK/cloud-licensing-web/pull/298#issuecomment-1641880722.
If the snackbar message was long or the screen width was small then the text was wrapping onto a newline, however so was the action button to close the dialog. The action button is now always on the right and vertically centre aligned with the message text.
Before:
After:
Open up storybook for Snackbar, set a long message or resize the screen width so the message wraps onto multiple lines and confirm close action button is as expected.

Snackbar flex-wrap

---

src/ThemeProvider/ThemeProvider.tsx

[Closes TD-2038](https://sce.myjetbrains.com/youtrack/issue/TD-2038/The-color-of-the-alert-title-in-dark-mode-is-mismatched)
- added root style to MuiAlertTitle class under the components
Tested by integrating into VIRTO.FLEET
Before
After

TD-2038 color of the alert title in dark mode mismatched

---

.github/workflows/test.yml
src/ActionDialog/ActionDialog.stories.tsx
src/Autocomplete/Autocomplete.stories.tsx
src/Autocomplete/Autocomplete.tsx
src/Autocomplete/Autocomplete.types.ts
src/DialogTitle/DialogTitle.stories.js
src/VehicleSelect/VehicleSelect.test.tsx
src/VehicleSelect/VehicleSelect.tsx
src/VehicleSelect/VehicleSelect.types.ts
src/VehicleSelectDialog/VehicleSelectDialog.stories.tsx
src/VehicleSelectDialog/VehicleSelectDialog.test.tsx
src/VehicleSelectDialog/VehicleSelectDialog.tsx
src/VehicleSelectDialog/VehicleSelectDialog.types.ts
src/VehicleSelectDialog/index.ts
src/index.ts

Closes [TD-2069](https://sce.myjetbrains.com/youtrack/issue/TD-2069/Create-add-vehicle-dialog)
Figma: https://www.figma.com/proto/B75H0DFTEiUFjJtehIKa8M/VIRTO.MODEL?node-id=522-57017&scaling=scale-down&page-id=0%3A1&starting-point-node-id=228%3A28915
- Created a new VehicleSelectDialog component
- Enables the "Add Vehicle" upon valid vehicle selection
- Added callback to return the currently selected vehicles
- Upgraded to node version 18 and upgraded the actions/setup-node action to the latest version
- Moved ActionDialog, DialogTitle, and VehicleSelectDialog components under the Dialog category from General
- Renamed selected vehicles to value, all gates to gates, on vehicle change to onChange, allVehicles to variants to be consistent with vehicleSelect Component
- Added a new prop …

TD 2069 vehicle select dialog

---

src/VehicleSelect/VehicleSelect.stories.tsx
src/VehicleSelect/VehicleSelect.test.tsx
src/VehicleSelect/VehicleSelect.tsx
src/VehicleSelect/VehicleSelect.types.ts
src/VehicleSelectDialog/VehicleSelectDialog.tsx

Contributes to [TD-1435](https://sce.myjetbrains.com/youtrack/issue/TD-1435/Multiselection-of-Vehicle-Variants-in-Data-Model-upload)
Fixed an issue I spotted when trying to make use of the [recently released](https://github.com/IPG-Automotive-UK/react-ui/pull/694) VehicleSelect component. There was an inconsistency with the input and output objects. We were passing in an object with a field `projectCode` but getting back and object with a field `project`. VIRTO.VEHICLE uses `projectCode` so it makes sense to stick with this so we can just pass data directly through.
Before:
After:
No manual testing is required here. The automated tests and type-checks already cater for this. If you do want to manually test something then you could `npm run storybook` and check you can still interact with …

Fixed inconsistency with project and projectCode

---

src/VehicleSelect/VehicleSelect.tsx

Contributes to [TD-1435](https://sce.myjetbrains.com/youtrack/issue/TD-1435/Multiselection-of-Vehicle-Variants-in-Data-Model-upload)
When trying to make use of the new VehicleSelect component in one of our apps I noticed we were getting this weird behaviour.
I've tracked it down to an issue with the bundler and known issue https://github.com/developit/microbundle/issues/945.
We were making use of spread syntax to get unique values in an array
```
const selectedProjects = [
...new Set(value.map(vehicle => vehicle.projectCode))
];
```
When bundled this was building down to this which is not the same.
```
var selectedProjects = [].concat(new Set(value.map(function (vehicle) {
return vehicle.projectCode;
})));
```
You can check the bundled code using `npm run build` and then inspecting …

Fix spread syntax bundling error with VehicleSelect

---

src/DeletableList/DeletableList.test.tsx
src/DeletableList/DeletableList.tsx
src/TransferList/TransferList.test.tsx

Closes [TD-2176](https://sce.myjetbrains.com/youtrack/issue/TD-2176/DeletableList-click-to-delete)
- Added onDelete callback to fire  when the user clicks on the Delete("X") button
- Fixed tests for the DeletableList component to delete items only when the list item ("X") button clicked
- As the DeletableList component is used inside TransferList. Fixed tests for the TransferList component to delete items only when the list item ("X") button clicked
- Now  onDelete Callback should be fired only when the list item ("X") button clicked

DeletableList delete icon button can only delete the list item

---

src/Status/StatusIcon/StatusIcon.stories.tsx
src/Status/StatusIcon/StatusIcon.types.ts
src/Status/StatusLabel/StatusLabel.stories.tsx
src/Status/StatusLabel/StatusLabel.types.ts
src/Status/statuses.ts

Contributes to [TD-2097](TD-2097)
Added a new status icon and label to support the case of "No Metrics" as per recently modified [Figma design](https://www.figma.com/proto/1PlPUZAHb4H74zmDZEceTy/VIRTO.RESULT?type=design&node-id=870-67181&t=4tc7qWoF9rHHOrQL-0&scaling=scale-down&page-id=870%3A56163&starting-point-node-id=870%3A67269) for RESULT.
Also tidied up the types for StatusIcon and StatusLabel so they can both reference the same list of status options.
Also updated so that the status dropdown options in Storybook are alphabetical.
N/A
StatusIcon
StatusLabel
* `npm run storybook` and check StatusIcon and StatusLabel components include the new option for no-metrics.

TD-2097 New status icon and label for "No Metrics"

---

src/Status/StatusCard/StatusCard.test.tsx
src/Status/StatusCard/StatusCard.types.ts

Contributes to [TD-2221](https://sce.myjetbrains.com/youtrack/issue/TD-2221/Different-definition-of-Result-in-VIRTO.RESULT-and-Quality-in-VIRTO.FLEET)
Implemented the `no-metrics` status for the StatusCard component. This modification is essential for obtaining the `No Metrics` status in FLEET, ensuring consistency with the statuses in RESULT.
N/A
Light mode:
Dark mode:
* `npm run storybook` and check StatusCard component includes the new option for no-metrics.

TD-2221 New status "No Metrics" for Card Status

---

src/UserAvatar/index.d.ts

Contributes to [TD-2030](https://sce.myjetbrains.com/youtrack/issue/TD-2030)
Changed the typedef for useColorMap.
- The error `TS2349: This expression is not callable` occurred because the function was expected to return directly a callable function but was returning an object with a getColor method.
- Changing the return type of `useColorMap` from an object with a getColor method to a directly callable function resolved this error.
- Before the change, to get a color, you had to call `useColorMap(names).getColor(name)`.
- After the change, you can simply call `useColorMap(names)(name)`.

Bug Fix - useColorMap incorrect typedef

---

src/LinePlot/LinePlot.tsx
src/SurfacePlot/SurfacePlot.tsx

Closes [TD-2238](https://sce.myjetbrains.com/youtrack/agiles/115-26/current?issue=TD-2238)
This PR changes the exponent label on x and y axis for Line and surface plots. Previously, Plotly would apply a prefix to the label to indicate the order of magnitude of the axis for either very large or very small numbers. This is not very informative for the us
er, thus it was decided to change it to exponents.
#
- Adds option to Line Plot and Surface plot components to display exponent in scientific notation. 
Currently, Plotly will scale the axis with a prefix indicating the order of magnitude. Here it uses "mu", which indicates and order of magnitude of 10^-6
Now it will instead use exponents in the axis scaling: 
This PR can be tested by using storybook to verify that the axis labels behave as …

TD-2238 Changed exponent format to scientific notation for Line and surface Plots.

---

src/Autocomplete/Autocomplete.stories.tsx
src/Autocomplete/Autocomplete.test.tsx
src/Autocomplete/Autocomplete.tsx
src/Autocomplete/Autocomplete.types.ts
src/Select/Select.jsx
src/Select/Select.stories.js

- Implemented functionality to support options arrays consisting of key-value pairs
N/A
Example:
`[
{ key: "option-a", value: "Option A" },
{ key: "option-b", value: "Option B" }
]`

Enhancement - Options to allow key value array

---

CONTRIBUTING.md

Introduction of a `CONTRIBUTING.md` file to IPG-Automotive/react-ui where the definition of which test framework will be used to perform tests on components

Adding a CONTRIBUTING file with a strategy for implementing tests

---

src/UserAvatar/UserAvatar.test.tsx
src/UserAvatar/UserAvatar.tsx
src/UserAvatar/UserAvatar.types.ts
src/UserMenu/UserMenu.test.tsx
src/UserMenu/UserMenu.tsx

While reviewing some recent VIRTO.ID migration work, it was noted that the UserAvatar component used in the UserMenu, and the UserAvatar component used elsewhere had different font sizes. I confirmed with @Sowbhagya-ipg that she would like them to be consistent.
Previously the `UserMenu` was creating its own internal `UserAvatar` component. I have switched this over to use our own `UserAvatar` component. This component now accepts an `sx` prop so that `UserMenu` can apply the additional styles that it needs. 
UserMenu
UserAvatar
You can test UserAvatar and UserMenu in storybook using lightmode and dark mode.
I have also added tests for both components to check font-size.

UserAvatar font-size consistency

---

src/Card/DetailCard/DetailCard.test.tsx
src/Card/DetailCard/DetailCard.tsx

contributes to: https://sce.myjetbrains.com/youtrack/issue/TD-1300/Clicking-the-label-chips-does-not-do-anything
raised in PR here:  https://github.com/IPG-Automotive-UK/virto/pull/434#pullrequestreview-1805702144
- updated label chip in the detail card to not be clickable. 
Confirmed with @Sowbhagya-ipg that the label should not be clickable in the detail card : https://github.com/IPG-Automotive-UK/virto/pull/434#issuecomment-1878623486
- check that the label chips are no longer clickable in the detail card component. 
- ~~[ ] Branch has been run in docker.~~
- ~~[ ] Appropriate tests have been added.~~

TD-1300 Label Chip in Detail Card

---

package-lock.json
package.json

Contributes to [TD-1555](https://sce.myjetbrains.com/youtrack/issue/TD-1555/Remove-material-ui-dropzone-dependency-from-react-ui)
While integrating TD-1555 in VIRTO, we noted that some apps had to install peerDependencies from react-ui that they did not necassarily need in production. e.g. VIRTO.TEST had to install react-dropzone even though it did not use any react-ui components that dependend on this, just to get the application to bundle. This became more prevalent when we stopped for installing dependencies and regenerated the package-lock.jsons for each app with a normal `npm install`.
I've changed all peerDependencies back to being dependencies in their own right. I've kept `react`, `react-dom`, `@mui/material`, `@emotion/react` and `@emotion/styled"` as peerDependencies as they are …

TD-1555 Replace peerDependencies with dependencies

---

package-lock.json
package.json
src/FileUploader/FileUploader.stories.tsx
src/FileUploader/FileUploader.test.tsx
src/FileUploader/FileUploader.tsx
src/FileUploader/FileUploader.types.ts

Contributes to [TD-2438](https://sce.myjetbrains.com/youtrack/issue/TD-2438/Cannot-manually-upload-vehicle-projects)
This PR adds validation pending state to the file uploader component. This is a new `isValidating` boolean prop which defaults to false. When set to true the component switches to a pending state where no new selections or deselections are possible. This will be used in applications that require additional file validation steps outside of the component.
In doing this I also fixed a typo with pointerEvents prop and added missing logic for multiple which got missed during https://github.com/IPG-Automotive-UK/react-ui/pull/802
N/A
@Sowbhagya-ipg was involved in the design of this new state and has seen the new behaviour shown below.
Single select …

TD-2438 file picker validation state

---

src/TreeViewList/TreeViewList.spec.tsx
src/TreeViewList/TreeViewList.stories.tsx
src/TreeViewList/TreeViewList.tsx
src/TreeViewList/TreeViewList.types.ts

This PR introduces the functionality which expands out the items in the tree which matches the search term.
- A new flag has been added `expandSearchTerm` which can be used to control the use the functionality e.g when false items would not be expanded on search
- When enabled the `searchTerm` is used to search through a tree structure and return an array of node IDs that match a given search term. This allows users to easily find and navigate to items in the tree.
- The search is case-insensitive, meaning it will match nodes regardless of whether the search term is in upper case, lower case, or a mix.
- If a child node matches the search term, the function ensures that its parent node is also included in the result so that the parent is also visible. 
You can test by using the searchTerm …

TreeViewList - expand search items

---

src/Card/TableCard/TableCard.jsx

Contributes to [TD-2464](https://sce.myjetbrains.com/youtrack/issue/TD-2464/Create-the-overview-page)
Making this change to address a comment on a common issue [here ](https://github.com/IPG-Automotive-UK/virto/pull/535#issuecomment-1934689650)
- Removig extra space and last border
Before
After
1. Check there is no extra space visible after last row in the Table Card

Remove extra bottom padding and border from TableCard component

---

package.json
playwright.config.ts
src/NoWrapTypography/NoWrapTypography.stories.tsx
src/NoWrapTypography/NoWrapTypography.test.tsx
src/NoWrapTypography/NoWrapTypography.tsx

This PR fixes the with the sx property which was not being applied to the component correctly. 
It also solves some usability issues with playwright tests e.g. if a test is force exited and `pm2` does not correctly teardown storybook, then subsequent test runs will work where they errored before.
N/A
N/A
- Make sure you can edit `sx` prop in storybook and it applies correctly. A vitest test has been added to confirm this,

NoWrapTypography sx prop does not work

---

src/LoadErrorMessage/LoadErrorMessage.tsx

Contributes to feedback left [here](https://github.com/IPG-Automotive-UK/virto/pull/551#issuecomment-1971293743)
The default props for a 404 LoadErrorMessage should not show a Go Back button.
> I talked it through with @Sowbhagya-ipg and we agreed to remove the button for 404. It doesn't do anything that the user can't already do in the browser better. We should only use the button to provide value to the user, e.g. page specific context - go to fleet overview if prototype not found.
Release notes (patch):
- `LoadErrorMessage` default properties for a 404 error no longer show a "Go Back" button.
Can check in the 404 story as per screenshots above.

Default to not showing a button on LoadErrorMessage 404

---

package-lock.json
package.json
src/AppLauncher/AppLauncher.tsx

Contributes to [TD-1854](https://sce.myjetbrains.com/youtrack/issue/TD-1854/Suppress-new-VIRTO-tab-opening-when-switching-apps)
Updated the AppLauncher component so that links to the current app I am in open in the current tab and new apps open in a new tab. Previously all links opened in a new tab but it was requested from @Sowbhagya-ipg that links to the current app should just do a page reload in the current window.
For example here I am currently in SCENE so clicking the SCENE app menu item should reload in the current window.
We did also discuss the idea of removing links for the current app I am in but it was decided instead to keep showing them but reload in the current window rather than new window.
N/A
N/A
I've released a pre-release and integrated it in to VIRTO as that's the …

TD-1854 Open current app link in the current tab

---

src/TreeViewList/TreeViewList.spec.tsx
src/TreeViewList/TreeViewList.tsx

Contributes to TD-2030
This PR has the following changes:
- Added a conditional rendering block in `TreeViewList.tsx` that checks if `treeDisplayItems.length` is 0, which indicates no search results.
- If there are no search results, a `Typography` component is rendered with the text "No search results.".
**Note**:
_Previously the message was "No parameters available" however since this Tree is now a separate component, the Tree can contain any type of data not just parameters, so we will use a generic message now._
_Before searching:_
_After searching:_
1. Navigate to the storybook page for the TreeViewList component with search functionality - **With Search**
2. Fill the search field with a search term that that will not return any results (e.g. xx)
3. Check that the "No search results" …

TreeViewList - No search results message implementation 

---

src/Wizard/Wizard.tsx

Contributes to [TD-2555](https://sce.myjetbrains.com/youtrack/issue/TD-2555/Create-Wizard-Layout)
In this [PR](https://github.com/IPG-Automotive-UK/virto/pull/632#issuecomment-2009111776) @Sowbhagya-ipg noticed that the spacing of title and wizard steppers is wrong and this affects all apps. This PR is to fix this.
- Reduced wizard title margin to 16px
Before
After
- Check the title margin is redued to 16px

TD-2555 - Wizard title margin reduced

---

src/SelectorButton/index.ts

- SelectorButton desciption property has now become optional, as we dont use descriptions in VIRTO.SCENE
N/A
N/A
N/A
~~- [ ] Branch has been run in docker.~~

Description field made optional on SelectorButton

---

package.json
src/Autocomplete/Autocomplete.stories.tsx
src/Autocomplete/Autocomplete.test.tsx
src/Autocomplete/Autocomplete.tsx
src/Autocomplete/Autocomplete.types.ts
src/Checkbox/Checkbox.jsx
src/Checkbox/Checkbox.stories.jsx
src/Checkbox/Checkbox.test.jsx
src/Checkbox/index.ts
src/LabelSelector/LabelSelector.d.ts
src/LabelSelector/LabelSelector.jsx
src/LabelSelector/LabelSelector.stories.jsx
src/LabelSelector/LabelSelector.test.jsx
src/NumberField/NumberField.jsx
src/NumberField/NumberField.stories.jsx
src/NumberField/NumberField.test.jsx
src/NumberField/index.ts
src/RadioButtons/RadioButtons.jsx
src/RadioButtons/RadioButtons.stories.jsx
src/RadioButtons/RadioButtons.test.jsx
src/RadioButtons/index.ts
src/SwitchField/SwitchField.jsx
src/SwitchField/SwitchField.stories.jsx
src/SwitchField/SwitchField.test.jsx
src/SwitchField/index.ts
src/TextField/TextField.stories.tsx
src/TextField/TextField.test.tsx
src/TextField/TextField.tsx
src/TextField/TextField.types.ts

Closes TD-2588
Add props to RUI components to make inputs optionally controlled or uncontrolled.
This pull request will allow us to use each input in an uncontrolled manner for new validated form components. The name field allows the validation library to manage the input fields.
- Add defaultValues/defaultChecked and a name prop to the following components
- Checkbox
- RadioGroup
- TextField
- Switch
- Autocomplete
No changes
View the uncontrolled stories in storybook. All components should function as normal and the initial render should render the defaultValue.

Uncontrolled input  component updates

---

src/TabPanel/TabPanel.spec.tsx
src/TabPanel/TabPanel.stories.tsx
src/TabPanel/TabPanel.tsx
src/TabPanel/TabPanel.types.ts

Closes [TD-2716](https://sce.myjetbrains.com/youtrack/issue/TD-2716)
This PR introduces two new props to the TabPanel component:
variant: This prop allows the user to specify the variant of the Tabs component within the TabPanel. The variant prop is passed down to the Tabs components, allowing tabs to be styled as "fullWidth" or "standard".
customChildren: This prop allows the user to pass custom children to the TabPanel component. The customChildren prop is rendered in the TabPanel component, allowing the user to add custom content to the panel. Such as a button which is not a tab.
- After approval the component will be tested in VIRTO via pre-release.
- Failed end-to-end test are a known issue.
_Full width variant tabs_
_Standard variant tabs_
_Custom Add to download button_
Use case: …

TD-2716 TabPanel - Add functionality to allow custom button in tab

---

src/FileUploader/FileUploader.stories.tsx
src/FileUploader/FileUploader.tsx
src/FileUploader/FileUploader.types.ts
src/Uploader/useUploader.ts

Breaking change.
Deprecates the old syntax for the `acceptedFiles` property of the `<FileUploader />` component.
The old syntax allowed a string[] of file extensions to be passed. Newer versions of the underlying react-dropzone dependency no longer support this instead opting to match the standard syntax defined [here](https://developer.mozilla.org/en-US/docs/Web/API/Window/showOpenFilePicker#specifications) and [here](https://react-dropzone.js.org/#!/Dropzone). This newer syntax required that mime-types are present, and takes the form of an object of mime-types vs. extensions.
Instead of 
```ts
{
acceptedFiles: [".txt", ".csv"]
}
```
the correct syntax would now be
```ts
{
acceptedFiles: {
"text/plain": [".txt"],
"text/csv": [".csv"]
}
}
```
For a while we've been supporting both …

Deprecate string[] syntax for acceptedFiles

---

src/Uploader/UploaderHeader.tsx

Closes [TD-2734](https://sce.myjetbrains.com/youtrack/issue/TD-2734/Align-FileUploader-title-and-delete-icon-centrally)
FIxing this [PR ](https://github.com/IPG-Automotive-UK/virto/pull/710#issuecomment-2102283563) feedback
- Changed titleVariant body font size `body2` to `body1` as per figma
- Making uploader title and delete icon vertically central aligned
Figma https://www.figma.com/file/0CVK945S1cs1ku0sUXcgv7/VIRTO.SCENE?type=design&node-id=2875-43915&mode=design&t=PVp626pSIo13y12G-0
Before
After
- Check the file uploader font size is 16px if titleVariant is `body`
- Check title and delete icon vertically central aligned

File uploader title and delete icon alignment

---

src/BulletGauge/BulletGauge.spec.tsx
src/BulletGauge/BulletGauge.stories.tsx
src/BulletGauge/BulletGauge.tsx
src/BulletGauge/BulletGauge.types.ts
src/BulletGauge/BulletGaugeClientOnly.tsx
src/BulletGauge/index.ts
src/LinePlot/LinePlot.types.ts
src/SurfacePlot/SurfacePlot.types.ts
src/index.ts
src/utils/common.ts

Closes [TD-2737](https://sce.myjetbrains.com/youtrack/issue/TD-2737)
Contributes to [TD-2030](https://sce.myjetbrains.com/youtrack/issue/TD-2030)
This PR introduces a new `BulletGauge` component. This component is a gauge chart that can be used to represent data in a compact, linear format. It's particularly useful for comparing the measure of a primary metric against one or more other metrics.
Features:
- The gauge is rendered using the `react-plotly.js` library.
- The color of the gauge bar changes based on the value: red for values less than 30, green for values greater than 70, and orange for values in between.
- The component accepts title, value, and suffix as props.
Other changes:
- `SurfacePlot` and `LinePlot`
- Changed interface to type
- Updated JSDoc comments format as they …

TD 2737 Create React UI Bullet Gauge component

---

src/ImageUploader/ImageUploader.tsx

Closes [TD-2765](https://sce.myjetbrains.com/youtrack/issue/TD-2765/Fix-ImageUploader-containers-wrong-spelled-CSS-property)
- `pointerEvenets` to `pointerEvents` to restrict user to click on seleced image to upload new one
- Check user is able to upload new image only after deleting uploaded one by clicking on delete button

Fix ImageUploader container's wrong spelled CSS property

---

src/FileUploader/FileUploader.stories.tsx
src/FileUploader/FileUploader.test.tsx
src/FileUploader/FileUploader.tsx
src/ImageUploader/ImageUploader.stories.tsx
src/ImageUploader/ImageUploader.test.tsx
src/ImageUploader/ImageUploader.tsx
src/ImageUploader/ImageUploader.types.tsx
src/Uploader/useUploader.ts

Closes [TD-2770](https://sce.myjetbrains.com/youtrack/issue/TD-2770/Add-loading-state-to-ImageUploader)
Added a new loading state to  `ImageUploader` component for better user experinece based on the feedback received [here](https://github.com/IPG-Automotive-UK/virto/pull/729#issuecomment-2122615753)
- Added `isUploading` prop to control loading state
- Added new loading state UI
- Added new `SingleFileLoading` story 
- Increased file size limit from `1MB`  to `1000MB`
- Added tests 
- Added new 2 different custom error messages
New error messages
- Run `pnpm storybook` on this branch
- Go to `ImageUploader` and check you can switch values of new `isUploading` prop
- When its true you should see line progress loading state UI with "ImageUploading" text

TD-2770 ImageUploader loading state

---

package.json
pnpm-lock.yaml

Contributes to : https://sce.myjetbrains.com/youtrack/issue/TD-2782/Flickering-of-Confirmation-Dialog-when-trying-to-delete-a-road-or-scenario
Forces the version of material-ui-confirm to version 3.0.12, in order to maintain existing confirm functionality across all apps. 
In version 3.0.13 of material-ui-confirm, dialogs are automatically closed when the calling component is unmounted. See: 
https://github.com/jonatanklosko/material-ui-confirm/blob/master/CHANGELOG.md#3013. This means that anywhere where we initiate the confirm dialog from any component that unmounts (in our case popovers) the dialog is instantly closed. 
This is the issue can be seen here: 
https://github.com/IPG-Automotive-UK/react-ui/assets/75164177/fee86923-61c8-4900-b955-0e873cfaf7dd
In SCENE I forced the version of …

TD-2782 Forces version of material-ui-confirm to 3.0.12

---

package.json
pnpm-lock.yaml
src/ActionDialog/ActionDialog.test.tsx
src/Autocomplete/Autocomplete.test.tsx
src/ImageUploader/ImageUploader.test.tsx
src/TreeViewList/TreeViewList.tsx

Closes [VE-49](https://sce.myjetbrains.com/youtrack/issue/VE-49)
This PR addresses the following issues:
1. Typescript errors for vi tests - added missing imports which fixed the errors
2. `TreeViewList` - x-tree-view latest dependency update to v7 had breaking changes, these changes are made here
- Migration notes: https://mui.com/x/migration/migration-tree-view-v6
3. `material-ui-confirm` - had [breaking changes](https://github.com/IPG-Automotive-UK/react-ui/pull/879), reverted back to previous version,  release v8.0.0 will address these
- Should no longer see errors in vi test files
- TreeViewList should continue to function as intended without any changes to UI or behavior

VE- 49 React UI updates for x tree view and vi test imports

---

src/ThemeProvider/ThemeProvider.tsx

This ensures that required asterisks on fields are rendered in red across the apps. The colour is the same in both light and dark mode and matches the default mui error colour.
- The asterisk was themed in the theme provider 
This should be viewable in the TextField multiline story or if a required prop is placed on any MUI input field.

Enhancement - Red asterisk

---

Dockerfile

Whilst doing other tasks I noticed we are still installing playwright in our Dockerfile used for tests but we no longer run the Playwright tests as of https://github.com/IPG-Automotive-UK/react-ui/pull/861. This step can take around a minute so I've removed it which will speed up all future test action runs.
You can see the time saved by comparing this action run with a previous one.
N/A
N/A
Nothing to test. As long as the GitHub action tests still pass then we're all good.

Remove playwright install from Dockerfile

---

src/Autocomplete/Autocomplete.tsx

There is a console error around the spreading of a key prop with Autocomplete options. I believe this was an existing defect. I have resolved it by ensuring the key prop is placed on the option after spreading the props.
- Added the key to the option list whether rendering object data or a string.
- Trigger the dropdown list on each Autocomplete story and check there are no console errors

Bugfix - Fix console error from spreading key prop

---

.github/workflows/chromatic.yml
.gitignore
README.md
package.json
pnpm-lock.yaml
src/Card/DetailCard/DetailCard.stories.tsx
src/Card/DetailCard/DetailCard.test.tsx
src/Card/SummaryCard/SummaryCard.stories.tsx

We've talked for a while that it would be a good idea to host the storybook environment somewhere so that it is quickly accessible, as well as having "deploy-previews" for react-ui PRs so that UI/UX designers can gain easy access.
This PR enables that by using the Chromatic (creators of storybook) hosting free tier to do so. There are no limits to how many iterations of storybook we can push to Chromatic. 
Their paid features include visual regression testing, UI reviews etc. which we could investigate in the future. For now I have disabled this functionality so that we get hosting and deploy previews only.
I've followed the recommended deployment practices which is to generate previews on push. This means we can access deployments using either of the following url syntaxes:
``` …
```

Add deploy-previews and persistent deployment using Chromatic

---

src/Breadcrumbs/Breadcrumbs.stories.tsx
src/Breadcrumbs/Breadcrumbs.tsx
src/NumberField/NumberField.tsx

Closes [TD-2849](https://sce.myjetbrains.com/youtrack/issue/TD-2849/RUI-BreadCrumbs-truncating-all-list-elements) & [TD-2850](https://sce.myjetbrains.com/youtrack/issue/VE-74/Style-and-spacing-issues-around-NumberFields-in-8.0.0-pre-release)
Changes breadcrumbs so only the final item is truncated and wrapped in a tooltip. Restores the default "normal" margin to NumberFields
- Update component to only use the truncated tooltip on the final item
- Update styles to prevent all other items from shrinking
- Add "normal" prop as default to NumberField
Check the story to ensure only one the last breadcrumb is truncated. Check that the NumberField has a margin by default in storybook.

Bug - TD-2849 Fix Breadcrumb and Numberfield visual defect

---

src/NumberField/NumberField.tsx

Closes [VE-75](https://sce.myjetbrains.com/youtrack/issue/VE-75/NumberField-defect-non-chromium-browsers)
This ensures that the NumberField label is always collapsed to prevent an overlap bug.
In non chromium browser, letters are not blocked from being entered on the NumberField. This exposes a MUI defect that allows the label to overlap the letters in the number input on blur.
- This pr uses the shrink boolean on InputLabelProps to prevent the label overlap bug on non chromium browsers
Old: 
New:
This has been approved by @Sowbhagya-ipg 
View in storybook and check that the label is always shrunk.

Bug - VE-75 NumberField label overlap

---

src/Autocomplete/Autocomplete.stories.tsx
src/Autocomplete/Autocomplete.test.tsx
src/Autocomplete/Autocomplete.tsx
src/Autocomplete/Autocomplete.types.ts

Contributes to [VE-22](https://sce.myjetbrains.com/youtrack/issue/VE-22/Complete-end-to-end-creation-of-a-vehicle)
Add access to the inputValue prop on Autocomplete.
This allows you to update the display value without encountering controlled to uncontrolled errors. This will be used in tandem with the defaultValue to update, display and pass a given value without controlling the component.
- Add the inputValue prop
- Add the prop to storybook
- Add a test
Update the inputValue prop on the read only story and ensure text updates in the field.

Add inputValue prop to Autocomplete

---

src/CardContent/FileDetails/FileDetails.stories.tsx
src/CardContent/FileDetails/FileDetails.test.tsx
src/CardContent/FileDetails/FileDetails.tsx
src/CardContent/FileDetails/FileDetails.types.ts

Add href and target props to FileDetails
Add story
Add test
Update types
Closes [VE-91](https://sce.myjetbrains.com/youtrack/issue/VE-91/Add-href-support-to-the-FileDetail-component)
Contributes to [TD-2863](https://sce.myjetbrains.com/youtrack/issue/TD-2863/Handle-api-errors-when-downloading-roads)
Adds href support to the FileDetails component.
This introduces
- a downloadLinkHref prop
- a downloadLinkTarget prop
- Replaces the button with an anchor when the href is provided
Check the file detail story that the button renders as an anchor and passes through the href. Ensure the other stories function with no change.

Enhancement - Add href support to FileDetails download button

---

src/Wizard/Wizard.stories.tsx
src/Wizard/Wizard.test.tsx
src/Wizard/Wizard.tsx
src/Wizard/Wizard.types.ts
src/Wizard/WizardSteps/WizardSteps.stories.tsx

Closes [TD-2915](https://sce.myjetbrains.com/youtrack/issue/TD-2915/Update-title-prop-of-Wizard-in-RUI-to-accept-JSX-and-string)
- Added support to accept element in `Wizard` component `tilte` prop
- Test added
- Fixed a type issue in `WizardSteps.stories` which causing the following error
With string
With element
How to open the preview to test? See screenshot
Check the new `WithTitleTypeElement` story in Wizard  renders with an JSX element for prop `title`. Also make sure string case still works as before.

TD -2915 Update wizard title prop to support element

---

package.json
src/FileUploader/FileUploader.test.tsx
src/FileUploader/FileUploader.tsx
src/ImageUploader/ImageUploader.test.tsx
src/ImageUploader/ImageUploader.tsx
src/Uploader/useUploader.ts

Contributes to [TD-2862](https://sce.myjetbrains.com/youtrack/issue/TD-2862/Validate-file-extensions-in-the-RUI-Uploader-component)
- We no longer render any file rejection messages on hover. This is because the DataTransferItem object we have access to during this event does not contain enough information to correctly validate the file. Instead we wait for the drop event.
- We now validate files based on their extension. react-dropzone internally will allow files that pass the mime-type check through so even if we say `{ acceptedFiles: { "text/plain": [".rd5"] } }`, `.txt` were still being accepted.
- Check that you do not get any errors on hovering with files. Validation should now only occur on drop.
- Check that for instance the `{ acceptedFiles: { "text/plain": [".rd5"] } }` case no …

TD-2862 FileUploader extension validation

---

src/FileUploader/FileUploader.stories.tsx
src/FileUploader/FileUploader.test.tsx
src/FileUploader/FileUploader.tsx
src/FileUploader/FileUploader.types.ts
src/ImageUploader/ImageUploader.tsx
src/Uploader/UploaderHeader.tsx
src/Uploader/UploaderHeader.types.ts
src/Uploader/useUploader.ts
src/Uploader/useUploader.types.ts

Closes [TD-2973](https://sce.myjetbrains.com/youtrack/issue/TD-2973/Update-RUI-FileUploader-to-add-disabled-prop)
- Adds a `disabled` property to the FileUploader component. When true, this removes and deletion button, disables any hover effects on the dropzone, and disables any ability to drag/drop files.
- Also fixed an issue with the FileUploader in darkmode where text was always white, even when in an error state.
Empty
Single file
Multi file
- Test that disabled renders and behaves correctly for empty / single file / multiple file. The Figma can be found [here](https://www.figma.com/proto/0CVK945S1cs1ku0sUXcgv7/VIRTO.SCENE?node-id=2875-43915&t=MrVx5Q7gmwWRp35R-1). You can set the disabled flag using the story controls.

TD-2973 Add disabled prop to FileUploader

---

src/Card/SummaryCard/SummaryCard.stories.tsx
src/Card/SummaryCard/SummaryCard.test.tsx
src/Card/SummaryCard/SummaryCard.tsx
src/Card/SummaryCard/SummaryCard.types.ts

Closes [TD-2979](https://sce.myjetbrains.com/youtrack/issue/TD-2979/Add-moreOptionsRef-prop-to-SummaryCard)
We are making this change here because of a required use case in this tikcet [TD-2960](https://sce.myjetbrains.com/youtrack/issue/TD-2960/Implement-LabelSelectorPopover). On click of card view more menu item(Labels) we need to open another popover which should be anchored to the three dots button to keep the anchorReference, this is possible only by creating a `ref` and pass it to the three dots button then use it as `anchorEl` to the Popover. 
- `moreOptionsRef` optional prop added
- A new story added for above use-case
- Test added for new prop
New story
Check new story is working as expected with new prop.

TD-2979 moreOptionsRef prop to Summarycard 

---

src/LabelSelector/LabelChip/LabelChip.test.tsx
src/LabelSelector/LabelChip/LabelChip.tsx
src/LabelSelector/LabelChipGroup/LabelChipGroup.spec.tsx
src/LabelSelector/LabelChipGroup/LabelChipGroup.stories.tsx
src/LabelSelector/LabelChipGroup/LabelChipGroup.tsx

Closes [TD-2998](https://sce.myjetbrains.com/youtrack/issue/TD-2998/LabelChipGroup-popover-stays-open-after-clicking-a-LabelChip)
* Intercept the onClick callback for labels which are shown in the overflow popper inside LabelChipGroup so we can also close the popper when one of them is clicked.
* Updated the existing story for label chip group overflowing parent so labels are clickable to allow this to be tested.
* Updated the Playwright test to check popper is closed when we click on a label chip.
N/A
N/A
Use Storybook to check the popper closes when you click a label. The overflowing parent story for label chip group can be used.
Run the Playwright tests. Note these need to be run locally as they are not currently part of the GitHub actions.
```
npx playwright install
npx playwright …
```

TD-2998 Close label popper on click

---

src/TruncatedTooltip/TruncatedTooltip.spec.tsx
src/TruncatedTooltip/TruncatedTooltip.stories.tsx
src/TruncatedTooltip/TruncatedTooltip.tsx
src/TruncatedTooltip/TruncatedTooltip.types.ts

Closes [TD-3048](https://sce.myjetbrains.com/youtrack/issue/TD-3048/Update-RUI-TruncatedTooltip-component-to-enable-showing-tooltip-when-element-not-truncated)
- adds an optional `alwaysShowTooltip` prop to the `TruncatedTooltip` component. Default value is false.
- If `alwaysShowTooltip` is true, we should show the tooltip even if the component is not truncated
- adds an optional `TooltipProps` prop to the `TruncatedTooltip` component. Default value is undefined.
- `TooltipProps` allows to pass through the props of MUI `Tooltip` to the component, enabling us to use these in the component.
Showcasing the tooltip being shown while not being truncated from the storybook:

TD-3048 Update RUI TruncatedTooltip component to enable showing tooltip when element not truncated

---

package.json
src/TruncatedTooltip/TruncatedTooltip.spec.tsx
src/TruncatedTooltip/TruncatedTooltip.stories.tsx
src/TruncatedTooltip/TruncatedTooltip.tsx
src/TruncatedTooltip/TruncatedTooltip.types.ts

v8.7.0 release

---

src/DialogTitle/DialogTitle.tsx

Closes [TD-3050](https://sce.myjetbrains.com/youtrack/issue/TD-3050/DialogTitle-close-button-misaligned)
This PR fixes the issue found with close button misalignment of `DialogTitle` component used in many places. This issue first noticed in `DeleteLabelDialog` in SCENE. This PR also fixes some unwanted scroll appearing with default story in storybook of this component.
- Removed the `width` property of `h2`(MUI DialogTitle) to fix the content scrolling
- Close button style updated fix alignment.
Before
in RUI
in SCENE
After
in RUI
- Use the deploy-preview to test this
- Make sure no scrollbar appears on dialog title stories and close button properly aligned to right
- Also no text overlapping with close button

TD-3050 - Fix the close button alignment

---

src/AppLauncher/AppLauncher.tsx
src/VirtoAppHeader/VirtoAppHeader.tsx

Closes [TD-3038](https://sce.myjetbrains.com/youtrack/issue/TD-3038/Update-AppLauncher)
- Added "VIRTO Status" link text at the bottom of  `AppLauncher`
- Added missing `px` in height calucation for `Drawer` in `VirtoAppHeader` which was causing missing padding bottom in the launcher when there is a scroller.
Figma: https://www.figma.com/design/5qkWskMGpXY38REVIDcJnW/Landing-Page?node-id=2480-13370&node-type=CANVAS&t=usvKg62evL72zXSb-0
VIRTO Status link in `AppLauncher`
- Check 'AppLauncher`  has new "VIRTO Sataus" link text at the bottom which opens in a new tab
- Check  'AppLauncher` renders with  "VIRTO Sataus" link in `VirtoAppLayout` and there is padding at the bottom if there is a scroller

TD-3038 Update app launcher

---

src/Status/StatusCard/StatusCard.stories.tsx
src/Status/StatusCard/StatusCard.tsx
src/Status/StatusCard/StatusCard.types.ts
src/Status/StatusIcon/StatusIcon.stories.tsx
src/Status/StatusIcon/StatusIcon.test.tsx
src/Status/StatusIcon/StatusIcon.tsx
src/Status/StatusIcon/StatusIcon.types.ts
src/Status/statuses.ts

Closes [TD-3037](https://sce.myjetbrains.com/youtrack/issue/TD-3037/Update-StatusCard)
- `Operational` and `Disrupted` statuses added to `statuses.ts`
- `StatusCard`  title and status `typography` updated as per Figma
- `Tooltip` added to `StatusIcon` with optional `title` prop
- New stories added for `tooltip`
- `StatusIcon` tests updated for `tooltip`
Figma: https://www.figma.com/design/5qkWskMGpXY38REVIDcJnW/Landing-Page?node-id=3559-32542&node-type=FRAME&t=usvKg62evL72zXSb-0
New statuses
Status Icon updated style with tooltip
- Check `StatusCard` typography and spacing is same as Figma now
- Check new Statuses are shown and working fine on `StatusCard` doc
- Check `Tooltip` is displayed on hover of icon if `title` prop exists

TD - 3037 Update status card

---

src/RoadPreview/RoadPreview.stories.tsx
src/RoadPreview/RoadPreview.tsx
src/RoadPreview/RoadPreview.types.ts

Closes [TD-3034](https://sce.myjetbrains.com/youtrack/issue/TD-3034/Add-new-RoadPreview-component-to-RUI)
Contributes to [TD-3034](https://sce.myjetbrains.com/youtrack/issue/TD-3034/Add-new-RoadPreview-component-to-RUI)
Added optional SX style props to RoadPreview component.
- Possibility to adjust the styles of the wrapper element of RoadPreview component.
N/A
We can change the SX properties so the styles are updated on RoadPreview wrapper element

TD-3034 Added Optional SX Props

---

src/Status/StatusCard/StatusCard.stories.tsx
src/Status/StatusCard/StatusCard.test.tsx
src/Status/StatusCard/StatusCard.tsx
src/Status/StatusCard/StatusCard.types.ts

Closes/Contributes [TD-3037](https://sce.myjetbrains.com/youtrack/issue/TD-3037/Update-StatusCard)
While working on this [TD-3039](https://sce.myjetbrains.com/youtrack/issue/TD-3039/Update-RUI-in-all-apps) i came to notice in FLEET under quality tab the `StatusCard` title size was not quite as the previous design, this was actually fixed in `StatusCard`. To fix this we are adding a `titleVariant` prop to `StatusCard`. We also noticed the `StatusCard` title is not taking care of long texts, to fix this i have wrapped `StatusCard` title within `TruncatedTooltip`.
Issue in FLEET
- Added optional `titleVariant` which defaults to `subtitle2`
- Added `WithGridLayout` story which shows  `StatusCard` in grid layout with a dynamically added with to the wrapper.
- Wrapped `StatusCard` title with …

TD-3039 Add titleVariant prop

---

src/RoadPreview/RoadPreview.stories.tsx
src/RoadPreview/RoadPreview.test.tsx
src/RoadPreview/RoadPreview.tsx
src/RoadPreview/RoadPreview.types.ts

Closes/Contributes [TD-3034](https://sce.myjetbrains.com/youtrack/issue/TD-3034/Add-new-RoadPreview-component-to-RUI)
Removed Label type from RoadPreview types and added the correct one, which is Label, but from LabelSelector component. Two of the properties in the removed type createdAt and updatedAt were redundant and causing problems in Virto, because this was not the appropriate type.
- Added the correct label type
- Removed createdAt and updatedAt from the stories as well
N/A
N/A
- ~I have tested the changes in Docker / a deploy-preview.~
- ~I have populated the deploy-preview with relevant test data.~

TD-3034 Remove redundant properties from RoadPreview types

---

src/Status/StatusCard/StatusCard.stories.tsx
src/Status/statuses.ts

Closes/Contributes [TD-3081](https://sce.myjetbrains.com/youtrack/issue/TD-3081/Rename-cancelled-status-to-aborted-in-RUI)
Changed status name from cancelled to aborted in RUI Status card component and in statuses config file.
Icon stays the same. 
- Renamed "Cancelled" to "Aborted" in Status Card
N/A
Before
After
N/A
- ~[ ] I have tested the changes in Docker / a deploy-preview.~
- ~[ ] I have populated the deploy-preview with relevant test data.~

TD-3081 Renamed Cancel status to Aborted

---

src/Status/StatusCountTable/StatusCountTable.tsx

Fixes an uncaught error from  [TD-955](https://github.com/IPG-Automotive-UK/react-ui/pull/955)
Cast the string keys to a type that is a keyof the object. This was done to fix an uncaught error that was merged to main. 
Detailed below is how it was missed and caught:
Currently on RUI the linting does not catch this type of error among some others. Running the type-checks also does not expose the error. The only way to see the error is by running a build.
Updates not in this PR but being made for the upcoming major release:
- Bring linting in line with VIRTO so these issues can be caught earlier
- Adding a build step to the github CI/CD to ensure this builds correctly before we attempt a release
- Add running a build to the release checks in the Readme.
The above changes will be made in a …

bug/Release v8.9.0 - "string can not be used to index object" build error 

---

src/Status/StatusCountBar/StatusCountBar.tsx

Closes: [TD-3097](https://sce.myjetbrains.com/youtrack/issue/TD-3097)
Contributes to: [TD-3065](https://sce.myjetbrains.com/youtrack/issue/TD-3065)
- Applied a change to the height of the count bar to be with right design.
- The height is now applied to each individual box that form the whole bar, and the padding is on the wrapper.
N/A
before:
after:
Check the padding and the height in the browser.

TD-3097 Fix of the heigth and padding of the ststus count bar

---

package.json
src/Status/StatusCountBar/StatusCountBar.types.ts
src/Status/StatusCountTable/StatusCountTable.types.ts
src/Status/StatusCountTable/index.ts

Contributes [TD-3111](https://sce.myjetbrains.com/youtrack/issue/TD-3111/Display-StatusCountBar-in-TestTable)
Changed Props of the StatusCountBar component, for the count object which currently is Record<Status, number>. This change is necessary, because there is an error currently in Virto Test. This error is caused by differences in types for status in ipguk/types and Status types in RUI. In RUI there are many types supported and listed below:
type Status = "aborted" | "completed" | "disrupted" | "errored" | "failed" | "no-metrics" | "not-ready" | "not-run" | "operational" | "passed" | "pending" | "queued" | "ready" | "running"
In ipguk/types there are the following status types: 
type Status = "aborted" | "completed" | "errored" | "not-ready" | "queued" | "ready" | "running";
This is a …

TD 3111 Add Status Count Bar Component Bug

---

package.json
src/Card/TableCard/TableCard.jsx

Closes [TD-3144](https://sce.myjetbrains.com/youtrack/issue/TD-3144/Adjust-the-width-of-each-Table-Data-in-Table-Row-in-Table-Card-component)
Contributes[TD-3128](https://sce.myjetbrains.com/youtrack/issue/TD-3128/Update-scenario-details-page)
Changed Table Card td element in Table row width to 50% instead of 100px, so the table data will be visualized in equal spacing.
- td width changed to equal in table row in TableCard component
N/A
Tested with pre-release branch in VIRTO Scene
Before
After
N/A
- ~[ ] I have tested the changes in Docker / a deploy-preview.~
- ~[ ] I have populated the deploy-preview with relevant test data.~

TD-3144 Equal width TableCard columns

---

package.json
src/ModelButton/ModelButton.test.tsx
src/ModelButton/ModelButton.tsx
src/ModelButton/ModelButton.types.ts

Closes [TD-3161](https://sce.myjetbrains.com/youtrack/issue/TD-3161/Edit-the-styles-of-ModelButton-in-React-UI)
Updated ModelButton to show status icon on top right of the button. Borders and background color also updated to match the status colors defined in figma, with new hover behaviour as well. Popup button also has now outlined style, matching the colors and background from the ModelButton component.
The style of the component when no status is passed remains the same.
- Updated ModelButton with status icon and background + borders
- Updated ModelButtonPopup with status icon with background + borders
- Old styles for when button is disabled or no children are still the same
Here is the …

TD-3161 Model Button Edit Styles

---

package.json
src/SearchBar/SearchBar.tsx
src/TransferList/TransferList.stories.tsx
src/TransferList/TransferList.test.tsx
src/TransferList/TransferList.tsx
src/TransferList/TransferList.types.ts

Closes [VE-160](https://sce.myjetbrains.com/youtrack/issue/VE-160/Update-TransferList-Component)
This PR updates the TransferList to be used to replace the application specific implementations in Vehicle, ID, and Data.
- Removes the old method of transferring on check
- Items are now selected for transfer on click
- Items are transferred on clicking a transfer button
- Add secondary labels
- Updated style to match new figma design
- Client side optimistic transfer with a callback function
- Controlled transfer to ignore default functionality
https://github.com/user-attachments/assets/804da284-0200-4d4d-b75c-45e2e6c0ad72
- Selected items transfer correctly
- Select all functions correctly
- The onTransfer callback is called correctly
- handleTransfer calls prop and does not change the UI
- …

VE-160 Update TransferList

---

package.json
src/LazyLoadImage/LazyLoadImage.stories.tsx
src/LazyLoadImage/LazyLoadImage.tsx
src/LazyLoadImage/LazyLoadImage.types.ts

Contributes to [TD-3243](https://sce.myjetbrains.com/youtrack/issue/TD-3243/Lazy-Loading-ProjectCodeCard-component)
- The `LazyLoadImage` was initially only used in static sized images. However, the ProjectCodeCard component showed that a dynamic sized component causes issues for the skeleton which is showed while the image loads. If the component changed size, the skeleton stayed the old size
- adds the new optional `autoFitSkeleton` prop to the LazyLoadImage to address this issue, default set to false
- when `autoFitSkeleton` is set to true, the skeleton will fill the available space in the bounding element. When it is false, the skeleton uses static size
- created a new storybook element where the `LazyLoadImage` is used inside a dynamically sized element
You can use the new storybook …

TD-3243 Lazy loading ProjectCodeCard component

---

package.json
src/Filter/SetFilterButton/SetFilterButton.tsx

Closes [TD-3264](https://sce.myjetbrains.com/youtrack/issue/TD-3264/Unable-to-navigate-cards-via-tab-key-when-grouped-by-project-code-Model-Year)
[Here the bug is linked
](https://github.com/IPG-Automotive-UK/virto/pull/1213#issuecomment-2511323751)
Changed "border" property for focus-active pseudo class to "outline", so this will prevent border to jump and move other elements, for example the grid elements in Project code cards and Model year cards in prototypes index.
- Fix for jumping border of Filter button for SidebarFilter component
N/A
Before video:
[before-border-jumping.zip](https://github.com/user-attachments/files/17978320/before-border-jumping.zip)
After video: …

TD-3264 Fix for tab focus jumping border

---

.github/workflows/test.yml
package.json

Contributes to [TD-3265](https://sce.myjetbrains.com/youtrack/issue/TD-3265/Plotly-incorrect-font)
Until now we have shipped source code (.ts and .tsx) files as part of the build. We can't really remember why we did this because we also ship js code and .d.ts type decleration files generated by `tsc` which is all that should be needed. The result of shipping this source code is that running type-checks in consuming applications that set `skipLibCheck=true` also type checks raw typescript files in node_modules (but correctly skips .d.ts). This led to a number of false positives in the type-checking e.g. VIRTO.ID failing type-checks due to Plotly components that it does not use. This was fixed for example by installing type dependencies that the application itself did not need (but RUI …

TD-3265 Do not ship sourcecode (.ts, .tsx)

---

src/Filter/LabelFilter/LabelFilter.tsx
src/Filter/sortLabelOptions.test.ts
src/Filter/sortLabelOptions.ts

Closes/Contributes [TD-3271](https://sce.myjetbrains.com/youtrack/issue/TD-3271/Label-filter-options-are-not-sorted-in-FLEET)
Added sorting algorithm for label filter options.
Added test cases for options sorting.
NA
NA
NA

TD-3271 Sort label filter options

---

package.json
src/ConfirmProvider/ConfirmProvider.test.tsx
src/ConfirmProvider/ConfirmationDialog.tsx

Contributes to [TD-2946](https://sce.myjetbrains.com/youtrack/agiles/115-40/current?issue=TD-2946)
- The Dialog component in `ConfirmationDialog.tsx` is now conditionally rendered based on the open prop.
- The goal of this change is to ensure the Dialog component is only rendered when open is true, improving performance by not mounting the component unnecessarily. This approach sacrifices the close animation but prioritizes simplicity and resource efficiency.
- Verify that the Dialog component is rendered only when open is true.
- Ensure that no Dialog component is present in the DOM when open is false.
-  ~I have included appropriate tests.~
-  ~I have populated the deploy-preview with relevant test data.~
-  ~I have tagged a UI/UX designer for review if this …

TD-2946 Scene Freezes On Deleting Scenario

---

src/VehicleSelector/VehicleSelector.test.tsx
src/VehicleSelector/VehicleSelector.tsx

Close [TD-3355](https://sce.myjetbrains.com/youtrack/issue/TD-3355/Clear-Button-Remains-Visible-in-Variant-Autocomplete-After-Clearing-Selection-RUI)
Removes the X close button when the variant select is cleared, it was only happening on the variant select
Adding UX @Sowbhagya-ipg 
n/a
before
After
~~- [ ] I have tested the changes in Docker / a deploy-preview.~~
~~- [ ] I have included appropriate tests.~~
~~- [ ] I have populated the deploy-preview with relevant test data.~~

TD-3355 - Fixes Clear button on Variant select when deselecting

---

src/index.ts

- Add the export back for NoWrapTypography that was removed
- ~[x] I have included appropriate tests.~
- ~[x] I have populated the deploy-preview with relevant test data.~

Add NoWrapTypography back into exports

---

package.json
src/Uploader/useUploader.ts

Closes/Contributes [TD-2730](https://sce.myjetbrains.com/youtrack/issue/TD-2730/Same-file-can-be-uploaded-multiple-times-in-ROAD)
- Added validation to prevent duplicate file uploads.  
- Improved error messaging for better user clarity.  
- Filtered out duplicate files before adding new ones.  
- Displayed a clear message listing duplicate file names.  
NA
tagging UI/UX @Sowbhagya-ipg 
BEFORE :
AFTER :
1. Pull the branch into your local machine.
2. Run `pnpm install`.  Run `pnpm storybook`.
3. In the Browser, navigate to the `File Uploader` ->  `with multiple files selected`.
4. Remove the default files.  Upload new files.
5. Attempt to upload the same file again.
**Expected Result :** 
You should see an error message in the drop-box.
~I have tested the changes …

TD-2730 Same file can be uploaded multiple times in ROAD

---

src/ActionDialog/ActionDialog.stories.tsx
src/ActionDialog/ActionDialog.test.tsx
src/ActionDialog/ActionDialog.tsx
src/ActionDialog/ActionDialog.types.ts

Closes: [TD-3383](https://sce.myjetbrains.com/youtrack/issue/TD-3383)
Contributes to: [TD-3369](https://sce.myjetbrains.com/youtrack/issue/TD-3369)
- Added disable property to the ActionDialog cancel button
- Added test for the cancel button disabling
- Added the property to the types and storybook
N/A
before:
after:
Check if the ActionDialog have disable for the cancel button - "cancelDisabled"
property

TD-3383 Add disable functionality to the cancel button of the ActionDialog

---

package.json

This change removes the need for pre-releases of `@ipguk/react-ui` instead allowing developers to install this dependency via git for testing. This matches the "pre-release" behaviour of some of our other dependencies e.g. `virto-utils`.
e.g.
`pnpm i github:IPG-Automotive-UK/react-ui#9688c62ab1c50dc7664c131ccf5292b216ff218b`
where the identifier after the `#` can be any git identifier (commit sha, branch name, git tag). We would always recommend installing a specific commit sha.
We're supporting two cases here:
- A developer installs a pre-release via git to test unpublished functionality.
- A developer installs a full-release via npm to integrate tested published functionality.
You can test installing via the commit hash in a VIRTO application. I tested in the remix-starter template but …

Allow installing via git

---

src/VehicleSelector/VehicleSelector.stories.tsx
src/VehicleSelector/VehicleSelector.test.tsx
src/VehicleSelector/VehicleSelector.tsx

Contributes [TD-3416](https://sce.myjetbrains.com/youtrack/issue/TD-3416/Gate-value-is-not-preselected-in-vehicle-selector-for-DATA-and-MODEL-when-there-is-just-one-gate)
Ad auto selection if there is only one gate
N/A
Storybook, test VehicleSelector with gates
In Virto MODEL
https://github.com/user-attachments/assets/ba21b0cc-bd31-43fb-a3ee-5e722c694b35
In Virto DATA
https://github.com/user-attachments/assets/01d46da3-a32f-4169-83c0-6265e535d6dd
PROOF Gate still works with Multi Gates
https://github.com/user-attachments/assets/6de53646-4383-4860-bed4-9e8255776e2d
Storybook, test VehicleSelector with gates
for Virto in MODEL & DATA
pnpm i github:IPG-Automotive-UK/react-ui#fe04f90ca361ab51dbcaaddc186736c04b4779aa
~~- [ ] I have populated the deploy-preview with …

TD-3416 add auto selection for gates for VehicleSelector in RUI

---

src/TransferList/TransferList.test.tsx
src/TransferList/TransferList.tsx

Closes: [TD-3359](https://sce.myjetbrains.com/youtrack/issue/TD-3359) 
Contributes to: [TD-3333](https://sce.myjetbrains.com/youtrack/issue/TD-3333) 
- Search bar is above the select all checkbox.
- We render always the search bar, not only when we have items in the list.
- How many "Selected" items text is now capitalized.
N/A
Before:
After:
- Check if the TransferList search bar is now on top of the select all checkbox
- Check if the Selected is now with capital "S"

TD-3359 TransferList UI improvements

---

package.json
src/DateLabel/DateLabel.stories.tsx
src/DateLabel/DateLabel.test.tsx
src/DateLabel/DateLabel.tsx
src/IconWithLabel/IconWithLabel.stories.tsx
src/IconWithLabel/IconWithLabel.test.tsx
src/IconWithLabel/IconWithLabel.tsx
src/IconWithLabel/IconWithLabel.types.ts
src/UserLabel/UserLabel.stories.tsx
src/UserLabel/UserLabel.test.tsx
src/UserLabel/UserLabel.tsx
src/UserLabel/UserLabel.types.ts

Contributes [TD-3377](https://sce.myjetbrains.com/youtrack/issue/TD-3377/Update-Overview-tab-content-with-the-values-and-details)
Contributes [TD-3376](https://sce.myjetbrains.com/youtrack/issue/TD-3376/Update-UI-structure-of-Data-Component-top-level)
`This was meant to be implemented in TD-3376 in the Header component, but as it is merged it will be tested in the current TD-3377`. It makes no difference and just the tooltip have to be tested and it can be checked with the commit of this branch installed in VIRTO Data, [this branch here](https://github.com/IPG-Automotive-UK/virto/pull/1394)
Don't forget to add tooltip prop as here if you want to test the tooltip in virto data:
https://github.com/IPG-Automotive-UK/virto/blob/enhancement/TD-3377-update-overview-tab/apps/data/web/src/views/se …

TD-3377 Update overview tab

---

src/LinePlot/LinePlot.tsx

Closes/Contributes [TD-2230](https://sce.myjetbrains.com/youtrack/issue/TD-2230/Result-plot-Y-axis-labelling-does-not-wrap)
- The event listeners for window resize have been removed, and the axis labels wrapping is calculated based on the initial size of the plot div.
N/A
This resolves re-rendering issue and navigating to other tabs in VIRTO.RESULT
https://github.com/user-attachments/assets/f84f0548-95d3-4ff9-baad-6533da5cee7d

TD-2230 Bug fix/td 2230 line plot re rendering issue

---

src/VehicleSelector/VehicleSelector.stories.tsx
src/VehicleSelector/VehicleSelector.test.tsx
src/VehicleSelector/VehicleSelector.tsx
src/VehicleSelector/VehicleSelector.types.ts

Closes/Contributes [TD-3419](https://sce.myjetbrains.com/youtrack/issue/TD-3419/Project-Code-and-Prototype-name-mandatory-validations-missing-in-Build-and-Fleet)
Added error handling and tests to VehicleSelector
Check empty inputs  error on blur. Check fields always display errors when set externally.
- ~[ ] I have tested the changes in Docker / a deploy-preview.~

TD-3419 vehicle selector errors

---

src/ThemeProvider/ThemeProvider.test.tsx
src/ThemeProvider/ThemeProvider.tsx

Contributes
[TD-3461](https://sce.myjetbrains.com/youtrack/issue/TD-3461/Documentation-preserves-light-mode-even-though-user-selects-system-mode-with-system-mode-being-setup-as-dark)
[TD-3462](https://sce.myjetbrains.com/youtrack/issue/TD-3462/When-System-Preference-is-selected-within-Virto-and-System-modedark-and-user-switches-the-system-mode-from-dark-to-light-the)
This PR resolves an issue with theme mode synchronization between VIRTO and the Docusaurus theme. Both were using the same localStorage key, theme, to set, update, and read the current theme mode.
Recently, we added support for the system mode in VIRTO, which is not supported by Docusaurus. This caused issues when switching to system mode while a document was open.
As an immediate fix, we are assigning different localStorage …

TD-3461 Mode Storage Key to default

---

src/VehicleSelector/VehicleSelector.stories.tsx
src/VehicleSelector/VehicleSelector.test.tsx
src/VehicleSelector/VehicleSelector.tsx
src/VehicleSelector/VehicleSelector.types.ts

Closes [TD-3479](https://sce.myjetbrains.com/youtrack/issue/TD-3479/VehicleSelector-error-handling)
Ensures errors appear onBlur. Adds a prop to force the validation of all fields
- Add a "validate" prop to validate active fields
- Ensure fields are validated on blur
- When validate prop is true, set all error states
In storybook, check that empty fields show an error on blur by default. Check that an error appears with the validate prop is set to true (there is a validate story). Check that errors disappear when the field has a valid value.
- ~[x] I have populated the deploy-preview with relevant test data.~

TD-3479 Vehicle Selector Errors

---

package.json
src/LinePlot/LinePlot.stories.tsx
src/LinePlot/LinePlot.tsx
src/LinePlot/LinePlot.types.ts

Closes [TD-3529](https://sce.myjetbrains.com/youtrack/issue/TD-3529/Update-LinePlot-to-support-multiple-data-sets)
This PR enhances `LinePlot`  by adding support for secondary data, enabling a combined view for multi-line plots.
- Added `ydataSecond` and `ydataSecond` optional props for secondary data set
- If `ydataSecond` and `ydataSecond` are avilable a second line will render with different color as per Figma
- Addded `legendNameFirst` and `legendNameSecond` to display Legend names
- New `Overlay Plots` story added
Figma: https://www.figma.com/design/s2NuBwBayu8144EGjBCi5d/VIRTO.DATA?node-id=7703-217643&t=OMsPT8a8Q9kRP4BX-0
Storybook
VIRTO.DATA
- Verify default story still works fine
- Verify `Overlay Plots` shows two lines if there are `ydataSecond` and `ydataSecond`, with same …

TD-3529 LinePlot supports secondary data set

---

package.json
src/LinePlot/LinePlot.tsx

Contributes [TD-3529](https://sce.myjetbrains.com/youtrack/issue/TD-3529/Update-LinePlot-to-support-multiple-data-sets)
This PR is to add a fix for a comment recieved [here](https://github.com/IPG-Automotive-UK/virto/pull/1505#issuecomment-2777879613)
- Only shows `x` and `y` values on Tooltip
Before
After
- Vefify `Legend` not shown with `LinePlot` marker tooltips

TD-3539 Remove legend showing in tooltip

---

package.json
src/LabelSelector/LabelChipGroup/LabelChipGroup.tsx

Closes/Contributes [VE-397](https://sce.myjetbrains.com/youtrack/issue/VE-397/Intermittent-UI-Lag-When-Applying-Scenario-Filters)
This PR improves the `LabelChipGroup` component by preventing unnecessary re-renders due to the `ResizeObserver`.
What’s Changed:
- Used `useMemo` to cache the sorted list (cachedSortedChips).
- Updated `useEffect` to depend on the cached list instead of the raw chips prop.
**Note**: Previously, the chips prop was used directly in the dependency array of the `ResizeObserver` effect. Since chips is usually a new array on each render, this caused the effect to infinite re-renders.
By `memoizing` the sorted array and using it in the dependency array, we ensure stable references, which keeps the `useEffect` from firing more than needed and improves performance. …

VE-397 UI lag when applying scenario filters

---

package.json
src/SurfacePlot/SurfacePlot.tsx
src/ThemeProvider/ThemeProvider.tsx

Closes/Contributes- [TD-3554](https://sce.myjetbrains.com/youtrack/agiles/115-26/current?issue=TD-3554)
This PR introduces a centralized color scale configuration for Plotly surface plots via the ThemeProvider.
- Added a new `plotlyColorScales` to the theme object.
- Refactored the `SurfacePlot` component to read the color scale from `theme.plotlyColorScale`
Tagging @Sowbhagya-ipg  to confirm the color scale usage aligns with design expectations.
Before
After
- Check that the SurfacePlot still renders correctly in Storybook.
- Confirm the color scale reflects the centralized theme config.
- ~I have populated the deploy-preview with relevant test data.~

TD-3354 Update SurfacePlot for Enhanced Visual Flexibility with Theme-Based Colorscale

---

package.json
src/VersionChip/VersionChip.stories.tsx
src/VersionChip/VersionChip.test.tsx
src/VersionChip/VersionChip.tsx

Closes  [TD-3527](https://sce.myjetbrains.com/youtrack/issue/TD-3527/Update-VersionChip-to-Support-Whole-Numbers)
Currently, the VersionChip only supports decimal formats like 1.2 ("major.minor"). Update the function to also allow whole numbers like 1.
1. Updated the regex to allow both whole numbers (1) and decimal numbers (1.2).
2. Modified the function to handle cases where the minor version is missing (defaulting it to "0" if needed).
NA
NA
Run `pnpm Storybook` , Go to `VersionChip`, then test the below .
1. **Whole Number Support**  
- Test with `1` → Should be accepted.
2. **Decimal Number Support**  
- Test with `1.0` → Should be accepted.
- Test with `1.2` → Should be accepted as is.  
4. **Invalid Format …

TD-3527 Update VersionChip to support single digits

---

package.json
src/Wizard/WizardSteps/WizardStep/WizardStep.stories.tsx
src/Wizard/WizardSteps/WizardStep/WizardStep.test.tsx
src/Wizard/WizardSteps/WizardStep/WizardStep.tsx

Closes [TD-3581](https://sce.myjetbrains.com/youtrack/issue/TD-3581/Limit-step-1-helper-text-characters-in-FLEET)
- Added function to truncate helper text if it exceeds 30 characters limit
- Added new story
- Added test to check `Tooltip` is eabled when characters exceeds.
Tested on FLEET
- Check the `WizardStep` component and add a helper text which has morethan 30 characters and make sure this text is trucated and on hover a `Tooltip` with full text shown
- There a new`WithTooltipAndHelperText` story  to test this

TD-3581- Truncate helpertext and add tooltip

---

package.json
src/LinePlot/LinePlot.tsx

Closes [TD-3579](https://sce.myjetbrains.com/youtrack/issue/TD-3579/Limit-legend-characters-in-LinePlot)
- Added ability to `LinePlot` to truncate legend charactors if it exceeds 30 characters limit 
Deploy-preview link to test on DATA and FLEET : http://k8s-deploypr-apigatew-2dbcc9a009-177696052.eu-west-2.elb.amazonaws.com/
- Go to `LinePlot` in deploy preview
- Go to `Overlay Plots` story
- Update `legendNameFirst` and `legendNameSecond` to a very long string and verify it tuncate on UI aftr 30 characters

TD-3579 - Limit legend characters in LinePlot

---

package.json
src/ThemeProvider/ThemeProvider.tsx

Closes/Contributes [TD-3499](https://sce.myjetbrains.com/youtrack/issue/TD-3499/MUI-DataGrid-border-colour-not-correct-in-dark-mode)
- Fixed the border color issue on MUI DataGrid in dark mode by applying solid color to the border
The MUI DataGrid border color looks different than its row border color even if the color value is same. This is due to the transparency of the border color. So, I have put a solid color value for the border in dark mode which solves the issue.
N / A
Before:
After:
- Run pnpm storybook to launch the Storybook environment
- Switch to the dark mode
- Navigate to General > ThemeProvider > DataGrid and verify the border color and row divider color change, matching to other border colors(e.g. in paper …

TD-3499 Fixed MUI datagrid border color not correct in dark mode
