IPG-Automotive-UK/react-ui

- package-lock.json
- package.json
- src/ChangePasswordDialog/ChangePasswordDialog.js
- src/ChangePasswordDialog/ChangePasswordDialog.stories.js
- src/ChangePasswordDialog/ChangePasswordDialog.test.js
- src/ChangePasswordDialog/index.js
- src/ChangePasswordForm/ChangePasswordForm.js
- src/ChangePasswordForm/ChangePasswordForm.test.js
- src/RequestPasswordResetForm/RequestPasswordResetForm.js
- src/RequestPasswordResetForm/RequestPasswordResetForm.stories.js
- src/RequestPasswordResetForm/RequestPasswordResetForm.test.js
- src/RequestPasswordResetForm/index.js
- src/index.js
###New
* ChangePasswordDialog - Dialog that requests user to reauthenticate using existing password, and also supply new password repeated.
* RequestPasswordResetForm - Simple form that prompts user for an email address to reset password.
* ChangePasswordForm - Callback has changed from onReset to onSubmit for consistency.
> Additional password reset components

- src/SearchBar/SearchBar.js
- src/SearchBar/SearchBar.stories.js
- src/SearchBar/SearchBar.test.js
- src/SearchBar/index.js
- src/index.js
- Added SearchBar component to react-ui
- This will need to me merged before merging the associated NGD pull request. 
closes #54
> Added SearchBar Component

- src/PasswordChangeDialog/PasswordChangeDialog.stories.js
- src/Select/Select.stories.js
- src/Snackbar/Snackbar.stories.js
- src/SwitchField/SwitchField.stories.js
Updated the following  Storybook stories to ensure that the controls work as expected in storybook: 
- SwitchField
- Snackbar
- Select
- PasswordChangeDialog
> Update storybook stories to update dynamic values

- .github/workflows/test.yml
- src/Loading/Loading.js
- src/Loading/Loading.stories.js
- src/Loading/Loading.test.js
- src/Loading/index.js
- src/index.js
Added a new component and its test
> Added new Loading component

- src/Slider/Slider.js
- src/Slider/Slider.stories.js
Exposed disabled property and added a new story for it.
> Add disabled property to Slider

- src/Color/Color.js
- src/Color/Color.stories.js
- src/Color/Color.test.js
- fixed issue where onChange was not actually passed the updated color value
- updated color component to be controlled, hex state is the only state left.
> fixed issue with color component not outputting values onChange

- src/RadioButtons/RadioButtons.js
- src/RadioButtons/RadioButtons.stories.js
- src/RadioButtons/RadioButtons.test.js
- src/RadioButtons/index.js
- src/index.js
Contributes to  https://github.com/IPG-Automotive-UK/instrument-designer/issues/8
New radio buttons group component.
> Radio buttons group

- src/Slider/Slider.js
- src/Slider/Slider.stories.js
* Fixed for vertical slider.
* Added more options for label position: "left" and "right" for vertical sliders.
> Fix vertical slider

- src/Checkbox/Checkbox.js
- src/Checkbox/Checkbox.stories.js
Added a new input argument for checkbox style.
> Expose checkbox style

- src/Slider/Slider.js
- src/Slider/Slider.test.js
Closes https://github.com/IPG-Automotive-UK/instrument-designer/issues/125.
Fixed the issue with the step size being < 1.
> Fixed the bug with the step value smaller than 1

- src/Slider/Slider.js
Contributes to https://github.com/IPG-Automotive-UK/instrument-designer/issues/99.
Updated Slider to not overflow it's parent container.
> Slider should not overflow its element width

- package-lock.json
- package.json
- src/MultiText/MultiText.js
- src/SwitchField/SwitchField.js
Fewof changes:
* disabled column sorting for MultiText component.
* removed cursor overwriting for the text in SwitchField component.
* installed latest x-data-grid library (which contains the fix for  entering 0 on numeric column (DataGrid))
> Disable sorting for MultiText 

- src/SwitchField/SwitchField.js
- src/SwitchField/SwitchField.stories.js
Added size prop to Switch. Default remains as medium (previously hardcoded).
> Switch size

- src/FeedbackForm/FeedbackForm.js
Replaced Add Icon with Message Icon.
> Changed Fab Icon

- src/ThemeProvider/ThemeProvider.js
Closes https://github.com/IPG-Automotive-UK/react-ui/issues/391
Swapped primary and secondary colors to match the new IPG website branding where the main primary colour is now the IPG dark blue.
I've done a local build and tested in one of our apps (mm) and it looks good.
> IPG website branding

- src/FeedbackForm/FeedbackForm.js
- src/RegistrationForm/RegistrationForm.js
- src/RegistrationForm/RegistrationForm.test.js
- src/UserAvatar/UserAvatar.js
- src/UserAvatar/UserAvatar.stories.js
- src/UserAvatar/UserAvatar.test.js
- src/UserAvatar/colorMap.js
- src/UserAvatar/index.js
- src/index.js
New avatar component for showing user image or initials.
https://github.com/IPG-Automotive-UK/identity-access-management/pull/144#issuecomment-1137343096
> Avatar component

- src/Sidebar/Sidebar.js
Fixes misalignment between appbar and sidebar 
Before: 
After:
> fixed spacing on sidebar header to align with appbar in apps

- src/SearchBar/SearchBar.js
- src/ThemeProvider/ThemeProvider.js
The border for the Search bar and color for the Scroll bar will be changed based on the mode
> Searchbar and scrollbar dark mode

- src/ThemeProvider/ThemeProvider.js
Styled scroll bar for the light mode to be consistent in both light and dark modes.
> styled scroll for light mode

- src/AlignVertical/AlignVertical.js
- src/AlignVertical/AlignVertical.stories.js
- src/AlignVertical/AlignVertical.test.js
- src/AlignVertical/index.js
New component, vertical version of AlignHorizontal.
Preview:
> Add vertical alignment controls component

- src/LabelSelector/LabelSelector.js
- src/LabelSelector/LabelSelector.stories.js
##Summary:
- Allows size to be set on autocomplete component
> added the ability to set size on autocomplete component

- src/MultiColor/MultiColor.js
Fixes issue with value not correctly being updated when picking a new color in the color picker for a given row. Also fixed the issue with color popover not anchoring to the current cell that is being edited.
> Multi-color popper

- src/Card/DetailCard/DetailCard.js
- src/Card/DetailCard/DetailCard.stories.js
- src/Card/DetailCard/DetailCard.test.js
- src/Card/FileCard/FileCard.js
- src/Card/FileCard/FileCard.test.js
- src/Card/SummaryCard/SummaryCard.js
Closes https://sce.myjetbrains.com/youtrack/issue/TD-1065/Create-new-Metadata-card-in-react-ui-part-2
- updated File card title to be accessible from other apps 
- updated summary Card width and height types
- updated image size in FileCard
> Card component minor updates

- src/ThemeProvider/ThemeProvider.js
- src/ToggleColorMode/ToggleColorMode.test.js
Updateded useEffect dependencies to fix dark mode switch issue.
Currently Theme Toggle button is constantly in light mode.
> Fix for dark/light theme issue

- src/ModelButton/ModelButton.js
- src/ModelButton/ModelButton.test.js
Fixed an issue with ModelButton component where a single child was not getting rendered. This was the cause of the issue I was having with the tests in https://github.com/IPG-Automotive-UK/react-ui/pull/515. Issue resolved and additional tests added to cover the children feature.
> Single child for ModelButton

- src/Wizard/Wizard.js
* Increases horizontal padding to 24px after discussion with Sowbhagya. This is the standard padding.
> Wizard padding

- src/Wizard/WizardActions/WizardActions.js
Correct negative margin for the parent padding
> WizardActions padding

- .storybook/preview-head.html
- src/AppHeader/AppHeader.js
- src/Sidebar/Sidebar.js
- src/Slider/Slider.stories.js
Closes https://sce.myjetbrains.com/youtrack/issue/TD-1523/Update-app-headers-to-include-correct-app-naming
- Header updated to match Figma
- Font import updated
- Making VIRTO logo clickable in header and opens in same tab
- IPG logo now open in a new tab
> header updated

- src/AppHeader/AppHeader.js
- src/AppHeader/AppHeader.test.js
- Bug fix in the latest react-ui release
> removed unwanted props causing an error

- src/Card/DetailCard/DetailCard.stories.js
- src/Card/FileCard/FileCard.js
- src/Card/FileCard/FileCard.test.js
- src/Card/SummaryCard/SummaryCard.js
- src/Card/SummaryCard/SummaryCard.stories.js
- src/Card/TableCard/TableCard.js
Closes https://sce.myjetbrains.com/youtrack/issue/TD-1320/Fix-the-width-of-the-scenario-and-road-cards-to-be-368px-wide
https://sce.myjetbrains.com/youtrack/issue/TD-1324/In-the-card-details-page-the-meta-data-column-widths-should-be-the-same-width-for-all-sections
https://sce.myjetbrains.com/youtrack/issue/TD-1326/Download-all-only-downloads-Road-TestRun
https://sce.myjetbrains.com/youtrack/issue/TD-1377/Label-extra-number-showing-cut-off-in-card-view-in-MM
Fixed Card height and width
Fixed Table row width in detail view 
Fixed Table row width in Card view
Changed download all files text to download project
> Card component updates

- src/ActionDialog/ActionDialog.js
- This PR includes a small bug fix for the AcionDIalog rerendering for each input change due to the styled component inside the action component
- To fix this removed and added dialog styling function to outside action dialog component
> removed and added styling dialog component to outside actiondialog

- src/Card/DetailCard/DetailCard.js
- src/Card/DetailCard/DetailCard.stories.js
- src/Card/FileCard/FileCard.js
- src/Card/TableCard/TableCard.js
- src/Card/TableCard/TableCard.stories.js
Closes [TD-1258](https://sce.myjetbrains.com/youtrack/issue/TD-1258/Updates-for-Card-Components-in-React-ui)
Figma: 
https://www.figma.com/proto/0CVK945S1cs1ku0sUXcgv7/VIRTO.SCENE?node-id=820-43226&scaling=scale-down&page-id=0%3A1&starting-point-node-id=623%3A34220&show-proto-sidebar=1
Few fixes in the Detail Card
- removed the fixed height of the card. The header stays fixed and the File column and Detail column scroll together. 
- Fixed padding for table card stack inside detail card
- Added Spacing and adjusted height when there are no labels
Preview After Integrating into MM
Preview After Integrating into SM
> Card component fixes

- package-lock.json
- package.json
- src/Card/SummaryCard/SummaryCard.test.js
- src/ConfirmProvider/ConfirmProvider.test.js
- Updated to the latest version of @testing/library/dom
- updated to the latest version of @testing/library/react
- fixed tests in the confirmProvider component and summary card component
- You should run the npm test to confirm that the tests work.
> Dependent bot updates/20 apr2023

- package-lock.json
- package.json
> updated deps to latest versions

- src/UserMenu/UserMenu.tsx
- src/UserMenu/UserMenu.types.ts
Closes [TD-1776](https://sce.myjetbrains.com/youtrack/issue/TD-1776/Fix-console-errors-in-react-ui)
- removed onchangePassword and onLogout props
- added UserAvatarProps
on npm run test should not see any console errors for userMenu component
> Fix console error for userMenu Component

- .storybook/decorators.tsx
- src/AppHeader/AppHeader.stories.tsx
- src/AppLayout/AppLayout.stories.tsx
- src/UserMenu/UserMenu.stories.tsx
- src/VirtoAppHeader/VirtoAppHeader.stories.tsx
- src/VirtoAppLayout/VirtoAppLayout.stories.tsx
Previously stories that had some kind of absolute or fixed positional layout escaped the bounds of their story cards on the docs page. 
- Adds a generic decorator for stories that suffer this issue to use. This wraps the story in a div with `{transform: "scale(1)}` which gets around this issue.
- Allows `sx` to be passed into the decorator to allow heights and widths to be set. e.g. for `AppBar` stories we need a minHeight of 56px, whereas for `AppLayout` stories, we want to ensure the layout renders at 100vh and 100vw sizing as the component is written to expect this.
- Applies this decorator to `AppLayout`, `AppHeader`, `VirtoAppLayout`, `VirtoAppHeader`.
- Applies a wrapper to a single story in `UserMenu` where we show it inside of an `AppBar`.
Before:
After:
Check that stories render …
> Improve AppHeader / AppLayout stories

- src/Status/StatusCard/StatusCard.tsx
Contributes to [TD-1999](https://sce.myjetbrains.com/youtrack/issue/TD-1999/Show-the-quality-tab-in-the-Fleet-based-on-the-Sanity-check-status)
Making changes based on the PR [comment](https://github.com/IPG-Automotive-UK/virto/pull/43#discussion_r1284481869) .
- Width and border radius updated as Figma
Figma: https://www.figma.com/file/myLitRxs9xgX0k1oV2qdqg/VIRTO.FLEET?node-id=887%3A38172&mode=dev
Before
After
> width and border radius updated as figma

- src/DeletableList/DeletableList.stories.tsx
- src/DeletableList/DeletableList.test.tsx
- src/DeletableList/DeletableList.tsx
- src/DeletableList/DeletableList.types.ts
- src/DeletableList/index.ts
- src/TransferList/TransferList.stories.tsx
- src/TransferList/TransferList.test.tsx
- src/TransferList/TransferList.tsx
- src/TransferList/TransferList.types.ts
- src/TransferList/index.js
- src/TransferList/index.ts
- src/index.ts
Closes [TD-2067](https://sce.myjetbrains.com/youtrack/issue/TD-2067/Create-new-DeletableList-component)
- Created a new "Lists" section to track all list related components
- Created a new DeletableList  component as per Figma
- Integrated DeletableList into TransferList
- Migrated TransferList to typescript
- Tests added
Figma
https://www.figma.com/file/s2NuBwBayu8144EGjBCi5d/VIRTO.DATA?node-id=207%3A25481&mode=dev
New DeletableList component
Integrated view in TransferList
> TD-2067 DeletableList component 

- src/Autocomplete/Autocomplete.tsx
- src/Autocomplete/Autocomplete.types.ts
- src/Common.types.ts
- src/LabelSelector/LabelSelector.jsx
- src/utils/common.ts
Added the use isOptionEqualToValue to fix the warning below:
This error started occurring after changes to the Autocomplete component was changed to also accept key value pairs as options.
With the use of the isOptionEqualToValue, we are now checking the value against the option based on the type of options being used:
- The function takes two parameters: `option` and `value`.
- It first checks if `option` is a `KeyValueOption` object using the `isKeyValueOption` type guard function. If `option` is a `KeyValueOption`, it compares `option.value` to `value`.
- If `option.value` is equal to `value`, it returns `true`, indicating that the option is equal to the value.
- If `option` is not a `KeyValueOption` (which means it's a string in this context), it compares `option` directly to `value`. …
> Autocomplete Component - use isOptionEqualToValue method

- package-lock.json
- package.json
- src/TreeViewList/TreeViewList.spec.tsx
- src/TreeViewList/TreeViewList.stories.tsx
- src/TreeViewList/TreeViewList.tsx
- src/TreeViewList/TreeViewList.types.ts
- src/TreeViewList/index.ts
Contributes to [TD-2030](https://sce.myjetbrains.com/youtrack/issue/TD-2030) Migrating VIRTO.DATA to Remix
The PR introduces a new TreeViewList component that renders a tree view list. This component can be used to display hierarchical data in a tree structure.
- The TreeViewList component accepts several props including items, selected, searchTerm, defaultExpanded, and onSelectionChange. These props allow for customization of the tree view list.
- The TreeViewList component supports tooltips. When a tree item is hovered over, a tooltip with the item's name and additional information is displayed.
- The TreeViewList component includes a search function that can filter the items in the tree view list based on a search term.
The JSON structure represents a list of items, where each item can …
> TreeViewList Component

- src/Status/StatusCard/StatusCard.stories.tsx
- src/Status/StatusCard/StatusCard.types.ts
- src/Status/StatusIcon/StatusIcon.types.ts
- src/Status/StatusLabel/StatusLabel.types.ts
- src/Status/statuses.ts
- src/Status/statuses.types.ts
Contributes to [TD-2453](https://sce.myjetbrains.com/youtrack/issue/TD-2453/Update-ipguk-react-ui)
- Updates any status derived component (StatusCard, StatusLabel, StatusIcon) to accept any available status. No need to artificially restrict ourselves here.
- Adds new queued and errored statuses.
- Removes deprecated submitted status.
Major version bump:
- Adds new `queued` and `errored` statuses. Removes `submitted` status. Applies to the `StatusCard` `StatusLabel` and `StatusIcon` components.
I've specifically highlighted the use-cases we have for the story being worked on here, but you can test all of the combinations in Storybook.
> TD-2453 Update available statuses

- src/LoadErrorMessage/LoadErrorMessage.tsx
Addresses feedback left: https://github.com/IPG-Automotive-UK/react-ui/pull/820#discussion_r1506054608
The default props for an error handling using a LoadErrorMessage component have been corrected with the correct ipg support link.
Check link in storybook.
> Fix default contactUrl for errors in LoadErrorMessage

- src/SearchBar/SearchBar.tsx
- src/SearchBar/SearchBar.types.ts
- src/TreeViewList/TreeViewList.stories.tsx
- src/TreeViewList/TreeViewList.tsx
- src/TreeViewList/TreeViewList.types.ts
- **TreeViewList**
- Sticky Search Bar: Implemented a fix that ensures the `SearchBar` remains fixed at the top when scrolling through the list. This enhances usability by keeping the search functionality accessible.
- Search Functionality: Resolved an issue where nodes matching the search criteria were not expanding.
- Height Prop: Added a height prop to `TreeViewListProps`, offering more control over the component's height. 
- onNodeToggle Prop: Modified the `onNodeToggle` prop to be optional, increasing the component's flexibility for use cases where toggle functionality is not required.
- Toggle Callback: Addressed a missing callback issue by adding the `onNodeToggle` callback upon node toggle actions.
- Theme Compatibility: Enhanced theme support by integrating theme colors, …
> Enhancement - TreeViewList improvements

- src/TreeViewList/TreeViewList.tsx
This PR introduces several optimisations and functional enhancements to the TreeViewList component. The changes aim to improve performance during search operations and ensure a more efficient experience when interacting with the tree, especially in scenarios where there are larger results for the search term. Previously when using the search, larger results seem to significantly slow down the tree nodes from expanding.
- **Optimized Recursive Functions**: Wrapped the `countLastChild` and `expandNodes` functions with` useCallback` to prevent unnecessary recreations on each render.
- **Debounce Logic Enhancement**: Modified the debouncing approach for `expandNodes` to ensure it's triggered appropriately, reducing excessive state updates and avoiding potential infinite loops.
- **State …
> TreeViewList -  Improved performance

- src/SelectorButton/SelectorButton.tsx
- The updated dropshadow CSS has been to the Selector Button component
N/A
This is the hover effect in storybook 
Run this branch locally then go into storybook and verify that the boxshadow works on hover correctly using the updated CSS.
~~- [ ] Branch has been run in docker.~~
> Add updated boxShadow to Selector Component

- src/TabPanel/TabPanel.spec.tsx
- src/TabPanel/TabPanel.stories.tsx
- src/TabPanel/TabPanel.tsx
- src/TabPanel/TabPanel.types.ts
- src/TabPanel/index.ts
- src/TreeViewList/TreeViewList.tsx
- src/index.ts
Closes TD - [TD-2593](https://sce.myjetbrains.com/youtrack/issue/TD-2593/Create-React-UI-Tabbed-Panel-component)
Contributes to [TD-2030](https://sce.myjetbrains.com/youtrack/issue/TD-2030/Migrating-VIRTO.DATA-to-Remix)
This PR introduces the TabPanel component, designed to render tabbed interfaces within the application. 
- **New Components**: Added the TabPanel component along with its type definitions and a Storybook story.
- **Storybook Updates**: Created a new Storybook story under Layout/TabPanel to demonstrate the component's functionality and provide examples of its usage.
**Features:**
-   Dynamic tab generation based on child elements.
-   External control of the active tab through a prop for greater flexibility.
**Usage:**
The TabPanel component can be used in any part of the …
> TD-2593 - Create React UI Tabbed Panel component

- src/VehicleSelector/VehicleSelector.spec.tsx
- src/VehicleSelector/VehicleSelector.stories.tsx
- src/VehicleSelector/VehicleSelector.tsx
- src/VehicleSelector/VehicleSelector.types.ts
- src/VehicleSelector/index.ts
Closes - [TD-2594](https://sce.myjetbrains.com/youtrack/issue/TD-2594)
Contributes to - [TD-2030](https://sce.myjetbrains.com/youtrack/issue/TD-2030)
This PR introduces a new VehicleSelector component. This component is used to select a vehicle based on various parameters such as project code, model year, vehicle variant, and gate. 
_This component is similar to VehicleSelector but Gate is not require here so it is made optional and also we are not using multiselect on all fields which removes the complexity._ 
Key features:
- Uses the Autocomplete component for selection.
- Allows for the selection of project code, model year, vehicle variant, and gate.
- Handles disabled states based on the selection of previous parameters.
- If no gates are passed in, the Gate field will be hidden.
- …
> TD-2594 Create React UI - Variant vehicle search component

- package.json
- src/TabPanel/TabPanel.tsx
- src/TreeViewList/TreeViewList.spec.tsx
- src/TreeViewList/TreeViewList.tsx
- src/TreeViewList/example-items.json
- src/index.ts
Closes [TD-2652](https://sce.myjetbrains.com/youtrack/issue/TD-2652/TreeViewList-component-improvements-and-bugs)
This PR addresses the following issues:
1. After a parameter is selected and then the top level component is collapsed, the selected parameter parameter was losing the selection
- Current selection state has been added to keep the selection active when opening/closing parent nodes
2. The selected child node was not covering the entire width.
- Extra padding removed
- Override the `.css-9l5vo-MuiCollapse-wrapperInne` class which had the `width` set to `"100%"` this was causing the issue of not covering the entire width, setting it to `auto` fixed the issue
3. There was a flicker in the UI when hovering over the uncovered area in the child nodes
- As the flickering was only …
> TD-2652 TreeViewList component - improvements and bugs

- package.json
- src/Autocomplete/Autocomplete.tsx
- src/Autocomplete/Autocomplete.types.ts
- src/PartSelector/PartSelector.spec.ts
- src/PartSelector/PartSelector.spec.tsx
- src/PartSelector/PartSelector.stories.tsx
- src/PartSelector/PartSelector.tsx
- src/PartSelector/PartSelector.types.ts
- src/PartSelector/index.ts
- src/VehicleSelector/VehicleSelector.stories.tsx
- src/VehicleSelector/VehicleSelector.tsx
- src/VehicleSelector/VehicleSelector.types.ts
- src/index.ts
- src/utils/common.ts
Closes [TD-2691](https://sce.myjetbrains.com/youtrack/issue/TD-2691)
This PR introduces a new component, `PartSelector` to the library. The `PartSelector` is a user interface component that allows users to select a part from a list of parts. It is designed to be flexible and reusable in different parts of the application.
1. **Part Name Selection**: The component provides an autocomplete dropdown that lists all the unique part names. Users can select a part name from this dropdown.
2. **Part Number Selection**: Based on the selected part name, the component provides a second autocomplete dropdown that lists all the part numbers associated with the selected part name. This dropdown is disabled until a part name is selected.
3. **Flexible Layout**: The component can be displayed in a row or …
> TD-2691 Create React UI Part Selector Component

- src/TreeViewList/TreeViewList.tsx
Closes [VE-64](https://sce.myjetbrains.com/youtrack/issue/VE-64)
This PR adds a tree connector line which visually represents the hierarchy and connection between parent and child nodes in the tree structure.
This exists in the current apps which are not using the TreeViewList component, but it was missed on this component.
Before:
Now:
Connector Lines:
-  Ensure that the vertical connector lines are displayed only for child items.
-  Verify that the lines are not shown for parent items.
-  Check that the lines are properly aligned and connect parent-child nodes visually.
> VE-64 TreeViewList add tree connector line

- src/Card/SummaryCard/SummaryCard.stories.tsx
- src/Card/SummaryCard/SummaryCard.test.tsx
- src/Card/SummaryCard/SummaryCard.tsx
- src/Card/SummaryCard/SummaryCard.types.ts
- src/CardContent/Infographic/Infographic.tsx
Closes [TD-2815](https://sce.myjetbrains.com/youtrack/issue/TD-2815) Update CardSummary component
Contributes to [TD-2784](https://sce.myjetbrains.com/youtrack/issue/TD-2784) Create Versions tab for road details
Removes duplicate code by integrating `Infographic` into `SummaryCard`. Adds ability to display `VersionChip`.
- Replaced `CardMedia` with `Infographic` in `SummaryCard`
- Added ability to include `VersionChip`
- Added test to check `SummaryCard` renders with media and `VersionChip`
- Removed `mediaHeight` and `mediaWidth`, where these values were used for calculations they were replaced with absolute values.
- Replaced `<Fragment>` with `<Stack>` to be able to pass tag 'id' as per QA testing process.
[Figma](https://www.figma.com/design/0CVK945S1cs1ku0sUXcgv7/VIRTO.SCENE?node-id=7 …
> TD-2815 update card summary component

- src/TabPanel/TabPanel.tsx
Fixed the TabPanel contents exceeding the parent of TabPanel.
-Added `flexGrow: 1` and `minHeight: 0`
~- [ ] Branch has been run in docker.~
~- [ ] Appropriate tests have been added.~
> Fix TabPanel exceeding parent size

- src/TabPanel/TabPanel.tsx
Added a border to the `TabPanel` component.
~- [ ] Branch has been run in docker.~
~- [ ] Appropriate tests have been added.~
> Fix TabPanel Styling

- .vscode/launch.json
- package.json
- src/Card/DetailCard/DetailCard.stories.tsx
- src/Card/DetailCard/DetailCard.test.tsx
- src/Card/DetailCard/DetailCard.tsx
- src/Card/DetailCard/DetailCard.types.ts
- src/Card/DetailCard/index.ts
- src/Card/SummaryCard/SummaryCard.test.tsx
- src/Card/SummaryCard/SummaryCard.tsx
- src/Card/index.ts
- src/LabelSelector/LabelChip/LabelChip.test.tsx
- src/LabelSelector/LabelChip/LabelChip.tsx
- src/LabelSelector/LabelChip/LabelChip.types.ts
- src/LabelSelector/LabelChipGroup/LabelChipGroup.spec.tsx
- src/LabelSelector/LabelChipGroup/LabelChipGroup.stories.tsx
- src/LabelSelector/LabelChipGroup/LabelChipGroup.tsx
- src/LabelSelector/LabelChipGroup/LabelChipGroup.types.ts
- src/LabelSelector/LabelChipGroup/index.ts
- src/LabelSelector/index.ts
- src/index.ts
Cherry pick of commits from https://github.com/IPG-Automotive-UK/react-ui/pull/895 as the release destination has changed from V8 to V7.9.1 so we can get this out sooner.
> TD-2774 Label overflow bug fix

- .vscode/launch.json
- package-lock.json
- package.json
- src/Card/DetailCard/DetailCard.stories.tsx
- src/Card/DetailCard/DetailCard.test.tsx
- src/Card/DetailCard/DetailCard.tsx
- src/Card/DetailCard/DetailCard.types.ts
- src/Card/DetailCard/index.ts
- src/Card/SummaryCard/SummaryCard.test.tsx
- src/Card/SummaryCard/SummaryCard.tsx
- src/Card/index.ts
- src/LabelSelector/LabelChip/LabelChip.test.tsx
- src/LabelSelector/LabelChip/LabelChip.tsx
- src/LabelSelector/LabelChip/LabelChip.types.ts
- src/LabelSelector/LabelChipGroup/LabelChipGroup.spec.tsx
- src/LabelSelector/LabelChipGroup/LabelChipGroup.stories.tsx
- src/LabelSelector/LabelChipGroup/LabelChipGroup.tsx
- src/LabelSelector/LabelChipGroup/LabelChipGroup.types.ts
- src/LabelSelector/LabelChipGroup/index.ts
- src/LabelSelector/index.ts
- src/TabPanel/TabPanel.tsx
- src/index.ts
A merge branch for main into release. Some errors merge conflicts occurred and have been resolved but require testing.
Please run storybook and check to ensure the components are working as you would expect.
> Merge main release into v8.0.0

- Dockerfile
- package.json
Freeze the lockfile for installation
Add packageManager config to package.json
This introduces an update to prevent issues between local pnpm and the version used in Docker. It also prevents mismatches between locally installed dependencies and docker installed dependencies following a defect.
> Update Dockerfile to use a standardised version of pnpm

- package.json
- src/FileUploader/FileUploader.stories.tsx
- src/FileUploader/FileUploader.test.tsx
- src/FileUploader/FileUploader.tsx
- src/FileUploader/FileUploader.types.ts
- src/ImageUploader/ImageUploader.test.tsx
- src/ImageUploader/ImageUploader.tsx
- src/Uploader/UploaderHeader.tsx
- src/Uploader/UploaderHeader.types.ts
- src/Uploader/useUploader.ts
- src/Uploader/useUploader.types.ts
> Release v8.3.0

- src/index.ts
Contributes to [TD-2804](https://sce.myjetbrains.com/youtrack/issue/TD-2804/Cannot-build-CRA-based-apps-with-latest-RUI)
This PR addresses an additional build issue discovered during pre-release testing, related to the Figure component which uses react-konva. This component was missed in the initial fix for TD-2804.
-- Commented out the Figure component export in the relevant file
-- This component was using react-konva, which was causing build errors in CRA-based apps
-- Resolves build errors in CRA-based apps
N/A
Builds with no errors in React UI
-- Needs testing in Pre-release to make sure it builds inside apps without build errors
> TD-2804-Comment-out-Figure-component-to-resolve-react-konva-build-issue

- src/TabPanel/TabPanel.tsx
Contributes [VE-130](https://sce.myjetbrains.com/youtrack/issue/VE-130/Scroll-restoration)
- Added className selector to tabpanel container
- To add the ScrollRestoration component to the overview page in Road, we need a unique identifier for the TabPanel. I have added a className selector to the TabPanel container.
Maybe a short description of what is not included and will come in future work where appropriate.
> VE-130/add-tabpanel-class-selector

- src/RoadPreview/RoadPreview.stories.tsx
- src/RoadPreview/RoadPreview.test.tsx
- src/RoadPreview/RoadPreview.tsx
- src/RoadPreview/RoadPreview.types.ts
> TD-3034 Remove redundant properties from RoadPreview types (#951)

- src/Status/StatusCountTable/StatusCountTable.stories.tsx
- src/Status/StatusCountTable/StatusCountTable.test.tsx
- src/Status/StatusCountTable/StatusCountTable.tsx
- src/Status/StatusCountTable/StatusCountTable.types.ts
- src/Status/StatusCountTable/index.ts
- src/Status/index.ts
- src/index.ts
Closes/Contributes [TD-3098](https://sce.myjetbrains.com/youtrack/issue/TD-3098/Add-StatusCountTable-component)
Created new RUI Status count table component, which will be used by Status Count Bar component for showing with delay information about the current statuses of a. The component is a table with title, and total statuses count in the header. Below as table rows are shown all statuses. Appropriate tests are added for the data, which populates the component and icons for the statuses.
- Created Status Count Table component
N/A
[Figma prototype ](https://www.figma.com/proto/WoHtIQKM6eLlOUuzK1zlpB/VIRTO.TEST?node-id=2853-11258&t=sfHgNt2O3kLh0HHA-1)
N/A
- ~[ ] I have tested the changes in …
> TD-3098 Create StatusCountTable Component

- package.json
- src/ThemeProvider/ThemeProvider.tsx
I keep seeing console.errors in VIRTO related to kebab-case CSS. Tracked it down to the ThemeProvider in RUI styling ToggleButton components.
No change.
Here is a codesandbox showing the latest release and the console.error:
https://codesandbox.io/p/devbox/magical-pasteur-d6jvj3?workspaceId=d18fc477-1ef6-4998-8c6d-abeab5c13cac
Here is a codesandbox running the prerelrease for this branch without the console.error:
https://codesandbox.io/p/devbox/naughty-joana-2jdgyz?workspaceId=d18fc477-1ef6-4998-8c6d-abeab5c13cac
- ~I have tagged a UI/UX designer for review if this PR includes UI/UX changes.~
> kebab-case not allowed

- package.json
- src/Status/StatusCountBar/StatusCountBar.stories.tsx
- src/Status/StatusCountTable/StatusCountTable.stories.tsx
- src/Status/statuses.ts
Closes  [TD-3186](https://sce.myjetbrains.com/youtrack/issue/TD-3186/React-UI-Update-Add-Aborting-Status-Label)
Adds the Aborting status for TEST, previously there was only an 'Aborted' status
Updated the stories to show the status in the relevant components.
Tagging UX into the PR @Sowbhagya-ipg 
N/A
Tests pass
~~- [ ] I have tested the changes in Docker / a deploy-preview.~~
~~- [ ] I have included appropriate tests.~~
~~- [ ] I have populated the deploy-preview with relevant test data.~~
> TD-3186 Add-Aborting-Status-Label Update aborting status

- .github/workflows/test.yml
Closes https://github.com/davelosert/vitest-coverage-report-action/issues/428#issuecomment-2481080451 bug that was raised against this Github action. Switches to the new configuration option rather than our own workaround.
Confirm [coverage report](https://github.com/IPG-Automotive-UK/react-ui/pull/979#issuecomment-2482198078) on this PR is correctly formatted and file links take you to the correct place.
- ~I have tested the changes in Docker / a deploy-preview.~
- ~I have populated the deploy-preview with relevant test data.~
- ~I have tagged a UI/UX designer for review if this PR includes UI/UX changes.~
> vitest-coverage-report-action v2.8.0

- src/IconWithLabel/IconWithLabel.stories.tsx
- src/IconWithLabel/IconWithLabel.test.tsx
- src/IconWithLabel/IconWithLabel.tsx
- src/IconWithLabel/IconWithLabel.types.ts
- src/IconWithLabel/index.ts
- src/index.ts
Contributes [TD-3196](https://sce.myjetbrains.com/youtrack/issue/TD-3196/Prototype-and-Scenario-Hover-Preview-in-VIRTO.TEST)
Closes [TD-3229](https://sce.myjetbrains.com/youtrack/issue/TD-3229/Create-new-IconWithLabel-Component)
- Created new component to render an Icon with an icon to ther right that can optionally be a link
- Wrote tests to ensure the component renders and works as expected
- Created story for storybook
1. In the CI/CD workflow of this PR open the rendered storybook
2. Navigate to `IconWithLabel`
3. Make sure that the component renders and inspect it if it matches [FIGMA](https://www.figma.com/design/WoHtIQKM6eLlOUuzK1zlpB/VIRTO.TEST?node-id=3593-28578&node-type=instance&t=NXB3LkURANcNlQ9c-0) At the time …
> TD-3229 Create `IconWithLabel` component

- src/IconWithLabel/IconWithLabel.stories.tsx
- src/IconWithLabel/IconWithLabel.test.tsx
- src/IconWithLabel/IconWithLabel.tsx
- src/IconWithLabel/IconWithLabel.types.ts
- src/IconWithLabel/index.ts
- src/index.ts
This PR is merging this staging branch with the already reviewed code directly into a release branch.
- #983
> Merge Staging/TD-3196 into 9.1.0 release

- package.json
- src/VehicleSelector/VehicleSelector.stories.tsx
- src/VehicleSelector/VehicleSelector.test.tsx
- src/VehicleSelector/VehicleSelector.tsx
- src/VehicleSelector/VehicleSelector.types.ts
Contributes [VE-152](https://sce.myjetbrains.com/youtrack/issue/VE-152/Edit-gateway-timing-functionality)
- Added a prop disabled to the VehicleSelector Component default is set to false
- Updated types, story
- Added tests
- When disabled is true all the autocomplete components should be diabled.
> VE-152 Added diable prop to the VehicleSelector component

- .github/workflows/test.yml
- package.json
> Release v9.0.4

- src/VehicleSelect/VehicleSelect.spec.tsx
- src/VehicleSelect/VehicleSelect.test.tsx
- src/VehicleSelect/VehicleSelect.tsx
- src/VehicleSelector/VehicleSelector.spec.tsx
- src/VehicleSelector/VehicleSelector.test.tsx
- src/VehicleSelector/VehicleSelector.tsx
Contributes [VE-151](https://sce.myjetbrains.com/youtrack/issue/VE-151/Add-Gateway-timing-functionality)
- Renamed label from "vehicle variant" to variant
as mentioned here https://github.com/IPG-Automotive-UK/virto/pull/1115#issuecomment-2519949026
Before
After
> VE-151 Renamed label from "vehicle variant" to variant

- .github/workflows/test.yml
- src/ImageUploader/ImageUploader.test.tsx
- src/ImageUploader/ImageUploader.tsx
Contributes [TD-3294](https://sce.myjetbrains.com/youtrack/issue/TD-3294)
ImageUploader was extended to also support SVGs
1. Open storybook
2. Navigate to the ImageUploader
3. Try to upload an svg, confirm you can see the svg after uploading it with no issues
~- [ ] I have included appropriate tests.~
~- [ ] I have populated the deploy-preview with relevant test data.~
~- [ ] I have tagged a UI/UX designer for review if this PR includes UI/UX changes.~
> TD-3294 Add SVG to Image Uploader

- src/TransferList/index.ts
- src/index.ts
Closes/Contributes [TD-53](https://sce.myjetbrains.com/youtrack/issue/VE-53/Migrate-VEHICLE-to-Remix)
Exports the type for a TransferListItem 
> VE-53 Export transfer list item props

- src/UserLabel/UserLabel.tsx
Contributes [TD-3339](https://sce.myjetbrains.com/youtrack/issue/TD-3339) User avatar for prototype preview changes when we delete a scenario in Test
- The font size for the user avatar in `UserLabel` has been decreased to 10px
Maybe a short description of what is not included and will come in future work where appropriate.
1. Load storybook
2. Make sure that the size of the font of the users initials in the user avatar is 10px in `UserLabel`, `PrototypePreview`, `ScenarioPreview`, `RoadPreview`
3. Make sure the size of the font remains 14px
~- [ ] I have included appropriate tests.~
~- [ ] I have populated the deploy-preview with relevant test data.~
> decrease the font size of the avatar in the `UserLabel` component

- package.json
- src/TextField/TextField.tsx
- src/TruncatedTooltip/TruncatedTooltip.stories.tsx
- src/TruncatedTooltip/TruncatedTooltip.tsx
Closes/Contributes [TD-3284](https://sce.myjetbrains.com/youtrack/issue/TD-3284/NoWrapTypography-truncation-ellipsis-doesnt-match-color-of-child)
- Added React.forwardRef to TruncatedTooltip component to allow ref passing.
Maybe a short description of what is not included and will come in future work where appropriate.
This is a manual recreation of #1032 to target the correct branch.
NA
NA
NA
> TD-3284 Truncated Tooltip

- Dockerfile
Relates to https://github.com/nodejs/corepack/issues/612#issue-2812166605. As noted in the ticket, the latest version of corepack has resolved the issue, but the version of corepack in our docker containers currently is not latest. Hence for now I've force installed latest. Next time we bump the nodeJS version in our dockerfiles we can re-assess.
- ~I have populated the deploy-preview with relevant test data.~
- ~I have tagged a UI/UX designer for review if this PR includes UI/UX changes.~
> Latest corepack

- src/utils/common.test.ts
- src/utils/common.ts
Closes [TD-3449](https://sce.myjetbrains.com/youtrack/issue/TD-3449/Dropdown-values-in-Vehicle-selector-components-are-not-sorted-in-ascending-order)
Update uniqueSortedArray utility function to sort in ascending order by default. 
Check the VehicleSelector component dropdowns are sorted in ascending order
- ~[x] I have tested the changes in Docker / a deploy-preview.~
- ~[ ] I have populated the deploy-preview with relevant test data.~
> TD-3449 Fix Sort Order

- src/LinePlot/LinePlot.tsx
Contributes [TD-3472](https://sce.myjetbrains.com/youtrack/issue/TD-3472/Grid-Line-colour-issue-in-Plot)
- Added `theme.palette.divider` color to `LinePlot` grid
Before
After
Tested on VIRTO.DATA
Before
After
- Verify the `LinePlot` grid color changed to `theme.palette.divider`
- ~[ ] I have populated the deploy-preview with relevant test data.~
> TD-3472 Fix grid line colour issue in Plot

- src/EmptyState/EmptyState.tsx
Closes [TD-3410](https://sce.myjetbrains.com/youtrack/issue/TD-3410/Integrate-the-RUI-Empty-state-component-to-VIRTO-Apps)
- Removed border for Empty state component. 
N/A
N/A
Before 
After 
> TD-3410 Removed border for Empty state component

- src/DifferenceChip/DifferenceChip.stories.tsx
- src/DifferenceChip/DifferenceChip.test.tsx
- src/DifferenceChip/DifferenceChip.tsx
- src/DifferenceChip/DifferenceChip.types.ts
- src/DifferenceChip/index.ts
- src/index.ts
Contributes [TD-3486](https://sce.myjetbrains.com/youtrack/issue/TD-3486/Implement-the-diffParameter-logic)
- This component is based on the material Chip. Added functionality to show a difference value with an icon.
- It shows a positive value with an ArrowDropUp icon and a negative value with an ArrowDropDown icon.
- It also supports showing a unit with the value.
- Added tests and stories
Figma: https://www.figma.com/design/s2NuBwBayu8144EGjBCi5d/VIRTO.DATA?node-id=8071-224782&t=s02qgxIRtvUCLbWT-0
After integrating in VIRTO.DATA 
1) The component should look same like in figma
2) It shows a positive value with an ArrowDropUp icon and a negative value with an ArrowDropDown icon
3) It also  should support showing a unit with the value.
> TD-3486 Added Difference chip component
